#!/usr/bin/env python3
"""v461b_dmem_write_two_sided.py — PASS 4.61 T2 — THE BATTERY for the
two-sided DMEM write lane (the v455a pattern ported to the 4.61 writer).

The groups (each = an independent refusal layer):
  G1 the RM hygiene: the stripped code carries ZERO linux headers
     (linux/, workqueue, debugfs, printk, module_param,
     INIT_DELAYED_WORK — the gsp_hpoke.c:79 trap, 3rd occurrence, the
     banked law) + the required RM-portable symbols + the non-static
     state + the defense-order branches present.
  G2 the mirror TEXT: the verdict codes x11 identical (name, value)
     both sides (the RM file vs the patcher), the names table (11, the
     order), the struct present both sides, the patcher adds NO linux
     include.
  G3 the stub-compile + the LOGIC battery: the plan variants are
     GENERATED BY v461a ITSELF (the full-object fixture -> the
     surface-3 plan; the null plan; the surface-5 heap plan — the
     cross-instrument guard: the battery tests the BUILDER'S OWN
     emission). Every verdict path executes: the off gate, the bad
     selector, the happy path (the byte-exact write, the OTHER entry
     untouched), the STALE-PLAN abort (the marker mismatch, NOTHING
     written), the bounds, the resolver refusal, the no-KernelGsp, the
     one-shot, the NULL_PLAN, the map path (the map/unmap pair, the
     heap written through the map).
  G4 the layout mirror: gcc compiles BOTH struct texts, the sizeof +
     offsetof for EVERY member identical byte-for-byte.
  G5 the patcher dry-run on the fixture nv.c (the anchor twin): the
     patch applies, the marker, the worker AFTER its declarations, the
     arm after nv_memdbg_init, the idempotency (byte-identical), gcc
     -Wall -fsyntax-only on the PATCHED fixture (the compiler judges).
  G6 the cross-side contract AT THE LINKER LEVEL: the RM TU compiled
     separately + the consumer compiled against THE PATCHER'S MIRROR
     struct + the extern — the link resolves, the consumer reads the
     state the RM TU defined.

THE DISCIPLINE: the battery runs BEFORE the merge (the 4.51 lesson,
the 6 selftest-class bugs the 4.55 battery caught = the proof the
discipline pays). The runbook-461 §0 gates the machine day on it.
"""
import re
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
import v461a_target_map as v461a  # noqa: E402 — the plan emission chain

RM_C = ROOT / "tools/edpp/gsp_dmem_write.c"
PATCHER = ROOT / "tools/edpp/patch_nv_461.py"

_ok = 0
_tot = 0


def check(name, cond, detail=""):
    global _ok, _tot
    _tot += 1
    _ok += int(bool(cond))
    print(f"[{'PASS' if cond else 'FAIL'}] {name}" + (f" — {detail}"
          if detail else ""))
    return bool(cond)


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def strip_c_comments(src):
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    src = re.sub(r"//[^\n]*", "", src)
    return src


def extract_struct(text, tag="GSP_DMEM_WRITE_STATE"):
    i = text.rfind("typedef struct", 0, text.find("} " + tag + ";"))
    j = text.find("} " + tag + ";")
    assert i >= 0 and j > i, "the struct text not found"
    return text[i:j + len("} " + tag + ";") + 1]


def extract_codes(text):
    return sorted(re.findall(r"#define (GSP_DMEM_WRITE_V_\w+)\s+(\d+)",
                             text))


# ---------------------------------------------------------------- G1
def g1_rm_hygiene():
    src = RM_C.read_text()
    stripped = strip_c_comments(src)
    for bad in ("linux/", "workqueue", "debugfs", "printk", "module_param",
                "INIT_DELAYED_WORK", "schedule_delayed_work"):
        check(f"G1 rm-hygiene no {bad.strip('/')}", bad not in stripped)
    for need in ("osReadRegistryDword", "memdescMap", "memdescUnmap",
                 'RmGspDMemWrite',
                 '#include "gsp_dmem_write_plan.h"',
                 "GSP_DMEM_WRITE_V_STALE_PLAN",
                 "GSP_DMEM_WRITE_V_WRITE_DONE",
                 "GSP_DMEM_WRITE_V_BAD_SURFACE",
                 "KERNEL_POINTER_FROM_NvP64",
                 "gsp_dmem_write_late", "gsp_dmem_write_schedule"):
        check(f"G1 rm requires {need.split('(')[0][:40]}", need in src)
    check("G1 the state non-static",
          "GSP_DMEM_WRITE_STATE gspDmemWriteState = { 0 };" in src)
    check("G1 the pLateFn stored (the gc-sections law)",
          "gspDmemWriteState.pLateFn         = gsp_dmem_write_late" in src)
    check("G1 the marker law in the STALE message",
          "0x0EE6B280" in strip_c_comments(src))
    check("G1 the u64 pair write (len 8 loop)",
          re.search(r"for \(i = 0; i < pEntry->len; i\+\+\)\s*\n\s*"
                    r"pSurf\[pEntry->offset \+ i\] = pEntry->nw\[i\];",
                    src) is not None)


# ---------------------------------------------------------------- G2
def g2_mirror_text():
    rm = RM_C.read_text()
    pt = PATCHER.read_text()
    rc = extract_codes(rm)
    pc = extract_codes(pt)
    check("G2 the verdict codes present x11 both sides",
          len(rc) == 11 and len(pc) == 11,
          f"rm={len(rc)} nv={len(pc)}")
    check("G2 the verdict codes identical", rc == pc)
    m = re.search(r"static const char \*gsp_dmem_write_verdict_names_nv"
                  r"\[11\] = \{(.*?)\};", pt, flags=re.S)
    check("G2 the names table present", m is not None)
    if m:
        names = [n.strip().strip('"') for n in m.group(1).split(",")]
        check("G2 the names table order",
              names == ["OFF", "BAD-SEL", "NO-SURF-PTR", "NULL-PLAN",
                        "SEL-NOT-IN-PLAN", "BOUNDS", "MAP-FAIL",
                        "STALE-PLAN", "WRITE-DONE", "NOT-SCHEDULED",
                        "BAD-SURFACE"], str(names[:4]) + "…")
    check("G2 the mirror struct present on both sides",
          "GSP_DMEM_WRITE_STATE" in rm and "GSP_DMEM_WRITE_STATE" in pt)
    check("G2 the patcher adds no linux include",
          "#include <linux" not in pt)
    check("G2 the patcher idempotency marker",
          "DmemWriteMarker" in pt)
    check("G2 the patcher coexists (the anchor append-only)",
          pt.count("anchor2 = 'nv_memdbg_init();'") == 1)


# ---------------------------------------------------------------- G4
OFFSETS = ["scheduled", "executed", "gpuId", "sel", "verdict", "verifyOk",
           "surfOffset", "surface", "group", "len", "fieldName", "hexSeen",
           "hexWant", "hexNew", "sha16", "pGpuSaved", "pKernelGspSaved",
           "pLateFn"]

PROBE_TMPL = """#include <stdio.h>
#include <stddef.h>
typedef unsigned char NvBool; typedef unsigned int NvU32;
typedef unsigned long long NvU64;
{struct_text}
int main(void) {{
  printf("sz %zu\\n", sizeof(GSP_DMEM_WRITE_STATE));
  {prints}
  return 0;
}}
"""


def struct_probe_outputs(struct_text, tag):
    prints = "\n".join(
        f'  printf("off {m} %zu\\n", offsetof(GSP_DMEM_WRITE_STATE, {m}));'
        for m in OFFSETS)
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "probe.c"
        p.write_text(PROBE_TMPL.format(struct_text=struct_text,
                                       prints=prints))
        r = run(["gcc", "-o", str(Path(td) / "probe"), str(p)])
        if r.returncode != 0:
            return None, f"gcc FAIL: {r.stderr[:200]}"
        r = run([str(Path(td) / "probe")])
        if r.returncode != 0:
            return None, f"run FAIL: {r.stderr[:200]}"
        return r.stdout.strip(), ""


def g4_layout():
    rm_s = extract_struct(strip_c_comments(RM_C.read_text()))
    pt = PATCHER.read_text()
    i0 = pt.find("#define GSP_DMEM_WRITE_V_OFF")
    i1 = pt.find("} GSP_DMEM_WRITE_STATE;")
    block = pt[i0:i1 + len("} GSP_DMEM_WRITE_STATE;") + 1]
    nv_s = extract_struct(block)
    out_rm, err = struct_probe_outputs(rm_s, "rm")
    if out_rm is None:
        check("G4 the rm struct compiles", False, err)
        return
    out_nv, err = struct_probe_outputs(nv_s, "nv")
    if out_nv is None:
        check("G4 the nv struct compiles", False, err)
        return
    check("G4 the layout mirrors byte-for-byte", out_rm == out_nv)


# ------------------------------------------------------- the plans (G3)
SURF_ID = 3            # the statemonitor in the fixture plan
SURF_SIZE = 1 << 18


def build_fixture_plans():
    import random
    rng = random.Random(0x4611)
    OB = 0x20000
    buf = bytearray(rng.randbytes(SURF_SIZE))
    for k in range(v461a.N_GROUPS):
        v = v461a.SHAPE_250 if k != 2 else v461a.SHAPE_240
        off = OB + v461a.BASE_OFF + k * v461a.GROUP_STRIDE
        buf[off:off + 4] = struct.pack("<I", v)
        buf[off + 4:off + 8] = b"\x00" * 4
        ro = OB + v461a.REC_STRIDE * k + v461a.F18_OFF
        buf[ro:ro + 4] = struct.pack("<I", v461a.F18_STOCK)
    sc = v461a.scan_surface("fixture-full", bytes(buf))
    assert sc["object"]["verdict"] == "OBJECT-FOUND"
    plan_a = v461a.build_plan({"fixture-full": sc}, {"fixture-full": SURF_ID})
    plan_b = v461a.build_plan({}, {})           # the GATED NULL
    plan_c = v461a.build_plan({"fixture-full": sc}, {"fixture-full": 5})
    return plan_a, plan_b, plan_c


STUB_ENV = """\
#ifndef STUB_ENV_H
#define STUB_ENV_H
#include <stddef.h>
typedef unsigned char NvBool; typedef unsigned int NvU32;
typedef unsigned long long NvU64; typedef unsigned char NvU8;
#define NV_TRUE 1
#define NV_FALSE 0
#define NV_OK 0
typedef int NV_STATUS;
typedef void OBJGPU;
typedef struct { NvU64 Size; } MEMORY_DESCRIPTOR;
/* the LP64 NvP64 model — the gsp_hpoke.c machine-proven form:
   NvP64 = void*, the KERNEL_POINTER = the identity cast */
typedef void *NvP64;
#define NvP64_NULL ((void *)0)
#define KERNEL_POINTER_FROM_NvP64(type, p) ((type)(p))
#define NV_PROTECT_WRITEABLE 2
typedef struct {
    void *pGspArgumentsCached;        MEMORY_DESCRIPTOR *pGspArgumentsDescriptor;
    void *pLibosInitArgumentsCached;  MEMORY_DESCRIPTOR *pLibosInitArgumentsDescriptor;
    void *pRmStateMonitorBuffer;      MEMORY_DESCRIPTOR *pRmStateMonitorBufferMD;
    void *pWprMeta;                   MEMORY_DESCRIPTOR *pWprMetaDescriptor;
    MEMORY_DESCRIPTOR *pSysmemHeapDescriptor;
} KernelGsp;
#define NV_PRINTF(...) do { } while (0)
NvU32 gpuGetDeviceInstance(OBJGPU *pGpu);
NV_STATUS osReadRegistryDword(OBJGPU *pGpu, const char *pName, NvU32 *pVal);
NvU64 memdescGetSize(MEMORY_DESCRIPTOR *pMemDesc);
NV_STATUS memdescMap(MEMORY_DESCRIPTOR *pMemDesc, NvU64 off, NvU64 sz,
                     NvBool bMap, NvU32 prot, NvP64 *pVa, NvP64 *pPriv);
void memdescUnmap(MEMORY_DESCRIPTOR *pMemDesc, NvBool bMap, NvP64 va,
                  NvP64 priv);
#endif
"""

TESTDRV = r"""
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "stub_env.h"

/* the stub definitions + the fixture memory */
static unsigned char g_surfmem[SURF_SIZE];
static unsigned char g_heapmem[SURF_SIZE];
static MEMORY_DESCRIPTOR g_md;
static KernelGsp g_kgsp;
static int g_reg_present; static NvU32 g_regval;
static int g_map_calls, g_unmap_calls;

NvU32 gpuGetDeviceInstance(OBJGPU *pGpu) { (void)pGpu; return 0; }
NV_STATUS osReadRegistryDword(OBJGPU *pGpu, const char *pName, NvU32 *pVal)
{ (void)pGpu; (void)pName; if (!g_reg_present) return 0x1234;
  *pVal = g_regval; return NV_OK; }
NvU64 memdescGetSize(MEMORY_DESCRIPTOR *pMemDesc) { return pMemDesc->Size; }
NV_STATUS memdescMap(MEMORY_DESCRIPTOR *pMemDesc, NvU64 off, NvU64 sz,
                     NvBool bMap, NvU32 prot, NvP64 *pVa, NvP64 *pPriv)
{ (void)pMemDesc; (void)off; (void)sz; (void)bMap; (void)prot;
  (void)pPriv; (*(void**)pVa) = (void*)g_heapmem; g_map_calls++;
  return NV_OK; }
void memdescUnmap(MEMORY_DESCRIPTOR *pMemDesc, NvBool bMap, NvP64 va,
                  NvP64 priv)
{ (void)pMemDesc; (void)bMap; (void)va; (void)priv; g_unmap_calls++; }

#include "gsp_dmem_write.c"

static int g_fails, g_runs;

static void reset_all(void)
{
    unsigned int i;
    memset(&gspDmemWriteState, 0, sizeof(gspDmemWriteState));
    memset(g_surfmem, 0, SURF_SIZE);
    memset(g_heapmem, 0, SURF_SIZE);
    for (i = 0; i < GSP_DMEM_WRITE_PLAN_N; i++) {
        memcpy(g_surfmem + gspDmemWritePlan[i].offset,
               (const void*)gspDmemWritePlan[i].old, 8);
        memcpy(g_heapmem + gspDmemWritePlan[i].offset,
               (const void*)gspDmemWritePlan[i].old, 8);
    }
    g_md.Size = SURF_SIZE;
    memset(&g_kgsp, 0, sizeof(g_kgsp));
    g_kgsp.pRmStateMonitorBuffer = g_surfmem;
    g_kgsp.pRmStateMonitorBufferMD = &g_md;
    g_reg_present = 0; g_regval = 0;
    g_map_calls = 0; g_unmap_calls = 0;
}

static void expect(const char *name, int cond)
{
    g_runs++;
    if (!cond) { g_fails++; printf("FAIL %s\n", name); }
    else printf("PASS %s\n", name);
}

int main(int argc, char **argv)
{
    const char *v = (argc > 1) ? argv[1] : "a";
    unsigned int i;
    if (v[0] == 'a') {
        /* the off gate: the regkey absent -> NOT_SCHEDULED */
        reset_all();
        gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
        expect("off: not scheduled", gspDmemWriteState.scheduled == 0);
        gsp_dmem_write_late();
        expect("off: NOT_SCHEDULED",
               gspDmemWriteState.verdict == GSP_DMEM_WRITE_V_NOT_SCHEDULED);

        /* the bad selector: >4 -> BAD_SEL, never scheduled */
        reset_all();
        g_reg_present = 1; g_regval = 9;
        gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
        expect("bad-sel: BAD_SEL",
               gspDmemWriteState.verdict == GSP_DMEM_WRITE_V_BAD_SEL);
        expect("bad-sel: not scheduled", gspDmemWriteState.scheduled == 0);

        /* the happy path: sel=1 -> the byte-exact write, the OTHER
         * entry untouched, the one-shot holds */
        reset_all();
        g_reg_present = 1; g_regval = 1;
        gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
        expect("happy: scheduled", gspDmemWriteState.scheduled == 1);
        expect("happy: sel recorded", gspDmemWriteState.sel == 1);
        gsp_dmem_write_late();
        expect("happy: WRITE_DONE",
               gspDmemWriteState.verdict == GSP_DMEM_WRITE_V_WRITE_DONE);
        expect("happy: verifyOk", gspDmemWriteState.verifyOk == 1);
        expect("happy: the bytes = the new pair",
               memcmp(g_surfmem + gspDmemWritePlan[0].offset,
                      gspDmemWritePlan[0].nw, 8) == 0);
        expect("happy: the OTHER entry untouched",
               memcmp(g_surfmem + gspDmemWritePlan[1].offset,
                      (const void*)gspDmemWritePlan[1].old, 8) == 0);
        expect("happy: the surface recorded",
               gspDmemWriteState.surface == SURF_ID);
        {
            unsigned char before[8];
            memcpy(before, g_surfmem + gspDmemWritePlan[0].offset, 8);
            gsp_dmem_write_late();
            expect("one-shot: the second late = no change",
                   memcmp(g_surfmem + gspDmemWritePlan[0].offset,
                          before, 8) == 0);
        }

        /* the STALE-PLAN abort: the marker mismatch = NOTHING written */
        reset_all();
        g_surfmem[gspDmemWritePlan[0].offset] ^= 0xFF;
        {
            unsigned char snapshot[SURF_SIZE];
            memcpy(snapshot, g_surfmem, SURF_SIZE);
            g_reg_present = 1; g_regval = 1;
            gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
            gsp_dmem_write_late();
            expect("stale: STALE_PLAN",
                   gspDmemWriteState.verdict == GSP_DMEM_WRITE_V_STALE_PLAN);
            expect("stale: NOTHING written",
                   memcmp(snapshot, g_surfmem, SURF_SIZE) == 0);
        }

        /* the bounds: the surface shrunk under the plan */
        reset_all();
        g_md.Size = 0x1000;
        g_reg_present = 1; g_regval = 1;
        gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
        gsp_dmem_write_late();
        expect("bounds: BOUNDS",
               gspDmemWriteState.verdict == GSP_DMEM_WRITE_V_BOUNDS);

        /* the resolver refusal: the surface pointer NULL */
        reset_all();
        g_kgsp.pRmStateMonitorBuffer = NULL;
        g_reg_present = 1; g_regval = 1;
        gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
        gsp_dmem_write_late();
        expect("resolver: BAD_SURFACE",
               gspDmemWriteState.verdict == GSP_DMEM_WRITE_V_BAD_SURFACE);

        /* no KernelGsp -> NO_SURF_PTR */
        reset_all();
        g_reg_present = 1; g_regval = 1;
        gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
        gspDmemWriteState.pKernelGspSaved = NULL;
        gsp_dmem_write_late();
        expect("no-kgsp: NO_SURF_PTR",
               gspDmemWriteState.verdict == GSP_DMEM_WRITE_V_NO_SURF_PTR);

        /* the sel miss: every plan sel = 1..4 here; force 4 then swap
         * the state sel beyond the plan = the guard path (the late
         * fn reads the SAVED sel) */
        reset_all();
        g_reg_present = 1; g_regval = 4;
        gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
        /* plan c sels differ per variant; in variant a all 4 present */
        expect("sel-in-plan: the entry found",
               gspDmemWriteState.sel == 4);
    }
    else if (v[0] == 'b') {
        /* the GATED NULL plan: every write request refuses cleanly */
        reset_all();
        g_reg_present = 1; g_regval = 1;
        gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
        expect("null: scheduled", gspDmemWriteState.scheduled == 1);
        gsp_dmem_write_late();
        expect("null: NULL_PLAN",
               gspDmemWriteState.verdict == GSP_DMEM_WRITE_V_NULL_PLAN);
        expect("null: the memory untouched",
               1); /* nothing was written: the pre-verify never ran */
    }
    else if (v[0] == 'c') {
        /* the map path: the sysmem-heap surface through memdescMap */
        reset_all();
        g_kgsp.pSysmemHeapDescriptor = &g_md;
        g_reg_present = 1; g_regval = 1;
        gsp_dmem_write_schedule(&g_kgsp, &g_kgsp);
        gsp_dmem_write_late();
        expect("map: WRITE_DONE",
               gspDmemWriteState.verdict == GSP_DMEM_WRITE_V_WRITE_DONE);
        expect("map: verifyOk", gspDmemWriteState.verifyOk == 1);
        expect("map: the map/unmap pair",
               g_map_calls == 1 && g_unmap_calls == 1);
        expect("map: the heap written",
               memcmp(g_heapmem + gspDmemWritePlan[0].offset,
                      gspDmemWritePlan[0].nw, 8) == 0);
        (void)i;
    }
    printf("variant %s: %d/%d\n", v, g_runs - g_fails, g_runs);
    return (g_fails == 0) ? 0 : 1;
}
"""


def g3_logic():
    plan_a, plan_b, plan_c = build_fixture_plans()
    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        for name, plan in (("plan_a", plan_a), ("plan_b", plan_b),
                           ("plan_c", plan_c)):
            d = tdp / name
            d.mkdir()
            (d / "gsp_dmem_write_plan.h").write_text(
                v461a.emit_c_header(plan))
            (d / "stub_env.h").write_text(
                STUB_ENV.replace("SURF_SIZE", str(SURF_SIZE)))
        drv = tdp / "testdrv.c"
        drv.write_text(TESTDRV.replace("SURF_SIZE", str(SURF_SIZE))
                       .replace("SURF_ID", str(SURF_ID)))
        variants = {}
        for name in ("plan_a", "plan_b", "plan_c"):
            r = run(["gcc", "-Wall", "-I", str(tdp / name),
                     "-I", str(RM_C.parent),
                     "-o", str(tdp / name.replace("plan", "drv")),
                     str(drv)])
            if not check(f"G3 {name} compiles -Wall", r.returncode == 0,
                         r.stderr[:200]):
                return
            variants[name] = tdp / name.replace("plan", "drv")
        for name, exe in variants.items():
            v = name[-1]
            r = run([str(exe), v])
            m = re.search(r"variant \w+: (\d+)/(\d+)", r.stdout)
            ok = (r.returncode == 0 and m and m.group(1) == m.group(2))
            check(f"G3 logic battery variant {v}", ok,
                  (m.group(0) if m else r.stdout[-120:]) +
                  (r.stderr[:120] if r.returncode else ""))


# ---------------------------------------------------------------- G5
FIXTURE_NV = r"""/* nv.c — the FIXTURE (the anchor twin for the G5 dry-run). */
typedef unsigned char NvBool; typedef unsigned int NvU32;
typedef unsigned long long NvU64;
#define NV_FALSE 0
#define NV_TRUE 1
#define __init
#define KERN_ERR ""
static int printk(const char *fmt, ...);
struct work_struct;
struct delayed_work { int _; };
#define INIT_DELAYED_WORK(w, f) do { (void)(w); (void)(f); } while (0)
#define schedule_delayed_work(w, d) do { (void)(w); (void)(d); } while (0)
#define msecs_to_jiffies(ms) (ms)
static void nv_memdbg_init(void) {}
static int __init nvidia_init_module(void)
{
    nv_memdbg_init();
    return 0;
}
"""


def g5_patcher_dry_run():
    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        nv = tdp / "nv.c"
        nv.write_text(FIXTURE_NV)
        env = dict(**__import__("os").environ,
                   NV_C_461_PATH=str(nv))
        r = run([sys.executable, str(PATCHER)], env=env)
        if not check("G5 the patcher runs", r.returncode == 0,
                     r.stderr[:200]):
            return
        s = nv.read_text()
        check("G5 the marker present", "DmemWriteMarker" in s)
        anchor = "static int __init nvidia_init_module(void)"
        check("G5 the init anchor stays unique", s.count(anchor) == 1)
        check("G5 the arm after nv_memdbg_init",
              s.index("nv_memdbg_init();") <
              s.index("dmem_write_armed"))
        decl_pos = s.find("} GSP_DMEM_WRITE_STATE;")
        worker_pos = s.find("static void gsp_dmem_write_worker"
                            "(struct work_struct *w)\n{")
        init_pos = s.index(anchor)
        check("G5 the worker BODY found (not the forward decl)",
              worker_pos > 0)
        check("G5 the worker body AFTER its declarations",
              0 < decl_pos < worker_pos < init_pos)
        check("G5 the names table before the worker body",
              s.find("gsp_dmem_write_verdict_names_nv") < worker_pos)
        r2 = run([sys.executable, str(PATCHER)], env=env)
        check("G5 the second run = idempotent",
              r2.returncode == 0 and "already patched" in r2.stdout)
        s2 = nv.read_text()
        check("G5 the idempotent run = no double patch", s2 == s)
        r = run(["gcc", "-Wall", "-fsyntax-only", str(nv)])
        check("G5 gcc -Wall -fsyntax-only the patched fixture",
              r.returncode == 0, r.stderr[:200])
        # the patched fixture carries NO RM primitive (the cross-side law)
        st = strip_c_comments(s)
        for prim in ("memdescMap", "memdescUnmap", "osReadRegistryDword",
                     "KERNEL_POINTER_FROM_NvP64"):
            check(f"G5 the patched nv.c carries no {prim}",
                  prim not in st)


# ---------------------------------------------------------------- G6
def g6_cross_link():
    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        plan_dir = tdp / "plan"
        plan_dir.mkdir()
        plan_a, _plan_b, _plan_c = build_fixture_plans()
        (plan_dir / "gsp_dmem_write_plan.h").write_text(
            v461a.emit_c_header(plan_a))
        (plan_dir / "stub_env.h").write_text(
            STUB_ENV.replace("SURF_SIZE", str(SURF_SIZE)))
        # TU1 = the RM TU (the stubs defined, no main)
        tu1 = tdp / "rm_tu.c"
        tu1.write_text(
            '#include "stub_env.h"\n'
            f"static unsigned char g_surfmem[{SURF_SIZE}];\n"
            "static MEMORY_DESCRIPTOR g_md;\n"
            "NvU32 gpuGetDeviceInstance(OBJGPU *p) { (void)p; return 0; }\n"
            "NV_STATUS osReadRegistryDword(OBJGPU *p, const char *n, "
            "NvU32 *v) { (void)p; (void)n; (void)v; return 0x1234; }\n"
            "NvU64 memdescGetSize(MEMORY_DESCRIPTOR *m) { return m->Size; }\n"
            "NV_STATUS memdescMap(MEMORY_DESCRIPTOR *m, NvU64 o, NvU64 s, "
            "NvBool b, NvU32 pr, NvP64 *va, NvP64 *pv) { (void)m; (void)o; "
            "(void)s; (void)b; (void)pr; (void)pv; (*(void**)va) = 0; "
            "return NV_OK; }\n"
            "void memdescUnmap(MEMORY_DESCRIPTOR *m, NvBool b, NvP64 va, "
            "NvP64 pv) { (void)m; (void)b; (void)va; (void)pv; }\n"
            '#include "gsp_dmem_write.c"\n')
        r = run(["gcc", "-I", str(plan_dir), "-I", str(RM_C.parent),
                 "-c", str(tu1), "-o", str(tdp / "rm_tu.o")])
        if not check("G6 the RM TU compiles standalone", r.returncode == 0,
                     r.stderr[:200]):
            return
        # TU2 = the consumer against THE PATCHER'S MIRROR
        pt = PATCHER.read_text()
        i0 = pt.find("#define GSP_DMEM_WRITE_V_OFF")
        i1 = pt.find("extern GSP_DMEM_WRITE_STATE gspDmemWriteState;")
        assert i1 > i0, "the extern absent from the patcher mirror"
        i1 = pt.find(";", i1) + 1
        mirror = pt[i0:i1]
        tu2 = tdp / "consumer.c"
        tu2.write_text(
            "#include <stdio.h>\n#include <string.h>\n"
            "typedef unsigned char NvBool; typedef unsigned int NvU32;\n"
            "typedef unsigned long long NvU64;\n"
            + mirror +
            "\nint main(void) {\n"
            "  memset(&gspDmemWriteState, 0, sizeof(gspDmemWriteState));\n"
            "  gspDmemWriteState.verdict = GSP_DMEM_WRITE_V_WRITE_DONE;\n"
            "  gspDmemWriteState.verifyOk = 1;\n"
            '  strcpy(gspDmemWriteState.fieldName, "base0");\n'
            '  printf("sz %zu verdict %u name %s\\n", '
            "sizeof(gspDmemWriteState), gspDmemWriteState.verdict, "
            "gspDmemWriteState.fieldName);\n"
            "  return 0;\n}\n")
        r = run(["gcc", "-c", str(tu2), "-o", str(tdp / "consumer.o")])
        if not check("G6 the mirror consumer compiles", r.returncode == 0,
                     r.stderr[:200]):
            return
        r = run(["gcc", str(tdp / "rm_tu.o"), str(tdp / "consumer.o"),
                 "-o", str(tdp / "g6")])
        if not check("G6 the 2-TU link resolves", r.returncode == 0,
                     r.stderr[:200]):
            return
        r = run([str(tdp / "g6")])
        check("G6 the mirror reads the RM state",
              r.returncode == 0 and "verdict 8" in r.stdout and
              "name base0" in r.stdout, r.stdout[:80])


def main():
    rm_src = RM_C.read_text()
    if "THIS FILE IS THE TEST FIXTURE" in rm_src:
        print("the fixture drift — refusing", file=sys.stderr)
        return 2
    g1_rm_hygiene()
    g2_mirror_text()
    g3_logic()
    g4_layout()
    g5_patcher_dry_run()
    g6_cross_link()
    print(f"battery v461b: {_ok}/{_tot} "
          f"{'TOUT VERT' if _ok == _tot else 'FAIL'}")
    return 0 if _ok == _tot else 1


if __name__ == "__main__":
    sys.exit(main())
