#!/usr/bin/env python3
"""v462b_md_probe_battery.py — PASS 4.62 T2 — THE BATTERY for the
two-sided ROUTE W read probe (the v455a/v461b pattern ported to the
memdesc-over-phys reader).

The groups (each = an independent refusal layer):
  G1 the RM hygiene: the stripped code carries ZERO linux headers
     (linux/, workqueue, debugfs, printk, module_param,
     INIT_DELAYED_WORK — the gsp_hpoke.c:79 trap, banked law) + the
     required RM-portable symbols + the non-static state + the
     pLateFn stored + THE WRITE-FREE LAW (no pSrc[i] = on any left
     side — the probe reads, never writes: the code IS the
     guarantee, the v454b law).
  G2 the mirror TEXT: the verdict codes x8 + the plausibility classes
     x8 identical (name, value) both sides (the RM file vs the
     patcher), the patcher's TWO names tables (8 + 8), the struct
     present both sides, the patcher adds NO RM primitive.
  G3 the stub-compile + the LOGIC battery: the plan variants are
     GENERATED BY v462a ITSELF (the green-fixture plan -> the emitted
     header; the null plan; the 2-window plan — the cross-instrument
     guard: the battery tests the BUILDER'S OWN emission). Every
     verdict path executes: the off gate, the bad selector, the happy
     path (the byte-exact copy, the map/unmap pair, the primitives),
     the 8 plausibility classes on planted fixtures (SEAL-ZERO /
     SEAL-FF / SEAL-CONSTANT / WPRMETA-MAGIC / ELF-MAGIC /
     HEAP-FREELIST / DEGENERATE / LIVE-UNKNOWN), the MAP-FAIL (the
     seal named, NOTHING read, the unmap never called), the one-shot,
     the no-GPU, the NULL plan, the second window (sel=2, the
     describe->map->copy chain with the per-window base).
  G4 the layout mirror: gcc compiles BOTH struct texts, the sizeof +
     offsetof for EVERY member identical byte-for-byte.
  G5 the patcher dry-run on the fixture nv.c (the anchor twin): the
     patch applies (the debugfs include, the decls, the arm, the
     worker AFTER its declarations), the marker, the idempotency
     (byte-identical), gcc -Wall -fsyntax-only on the PATCHED fixture
     (the compiler judges — against the stub linux headers, the
     syntax-only judgment the fixture twin provides).
  G6 the cross-side contract AT THE LINKER LEVEL: the RM TU compiled
     separately + the consumer compiled against THE PATCHER'S MIRROR
     struct + the extern — the link resolves, the consumer reads the
     state the RM TU defined.

THE DISCIPLINE: the battery runs BEFORE the merge (the 4.51 lesson —
the batteries caught 8 bugs in 4.61, 11 in 4.55: the proof the
discipline pays). The runbook-462 §0 gates the machine day on it.
"""
import os
import re
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
import v462a_wpr2_read as v462a          # noqa: E402 — the plan emission

RM_C = ROOT / "tools/edpp/gsp_wpr2_read.c"
PATCHER = ROOT / "tools/edpp/patch_nv_462.py"

_ok = 0
_tot = 0

# the stub-scale window geometry (the battery's fixture world — the
# REAL plans carry the REAL FB addresses; the stub memory indexes by
# the described base, so the fixture plans = the small bases)
F_WS = 0x100000          # gspFwWprStart
F_WE = 0x200000          # gspFwWprEnd
F_FB = 0x1000000         # fbSize
F_HOFF = 0x110000        # gspFwHeapOffset (ABS survives: [0x110000,
                         # +0x40000) inside [0x100000, 0x200000])
F_HSZ = 0x40000
F_FWOFF = 0x150000
F_BOOTBIN = 0x180000
F_FRTSOFF = 0x190000
F_FRTSZ = 0x10000
FBMEM_SIZE = 2 << 20     # the stub FB memory (base-indexed)


def check(name, cond, detail=""):
    global _ok, _tot
    _tot += 1
    _ok += int(bool(cond))
    print(f"[{'PASS' if cond else 'FAIL'}] {name}" + (f" — {detail}"
          if detail else ""))
    return bool(cond)


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def strip_c_comments(src):
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    src = re.sub(r"//[^\n]*", "", src)
    return src


def extract_struct(text, tag="GSP_WPR2_READ_STATE"):
    i = text.rfind("typedef struct", 0, text.find("} " + tag + ";"))
    j = text.find("} " + tag + ";")
    assert i >= 0 and j > i, "the struct text not found"
    return text[i:j + len("} " + tag + ";") + 1]


def extract_codes(text, prefix="GSP_WPR2_READ_(?:V|C)_"):
    return sorted(re.findall(rf"#define ({prefix}\w+)\s+(\d+)", text))


# ------------------------------------------------------- the fixture plans

def fixture_fields(**over):
    """The stub-scale green GspFwWprMeta field dict (the v462a
    fixture law, rescaled: the structural relations IDENTICAL)."""
    f = {
        "magic": v462a.META_MAGIC, "revision": v462a.META_REVISION,
        "gspFwRsvdStart": 0x1F0000, "nonWprHeapOffset": 0x1F0000,
        "nonWprHeapSize": 0x10000,
        "gspFwWprStart": F_WS, "gspFwHeapOffset": F_HOFF,
        "gspFwHeapSize": F_HSZ, "gspFwOffset": F_FWOFF,
        "bootBinOffset": F_BOOTBIN, "frtsOffset": F_FRTSOFF,
        "frtsSize": F_FRTSZ, "gspFwWprEnd": F_WE,
        "fbSize": F_FB, "bootCount": 1,
        "gspFwHeapFreeListWprOffset": 0x1000,
        "verified": v462a.META_VERIFIED,
    }
    f.update(over)
    return f


def fixture_plan(f, s4_regions=None):
    """The windows from the fixture fields (the v462a math itself)."""
    wins = v462a.compute_windows(f, s4_regions=s4_regions)
    return wins


def build_fixture_plans():
    """The THREE variants (the v461b cross-instrument law — the
    battery tests v462a's OWN emission):
      plan_a  the single ABS survivor (the green fixture)
      plan_b  the GATED NULL plan (no windows)
      plan_c  the 2-window plan (the ABS + the S4 region — sel=2
              exercises the per-window describe->map->copy chain)
    """
    f_a = fixture_fields()
    wins_a = fixture_plan(f_a)
    assert (len(wins_a["survivors"]) == 1 and
            wins_a["survivors"][0]["win_class"] == v462a.WIN_ABS), \
        "the fixture-a model drift — refusing"

    wins_b = {"survivors": []}

    f_c = fixture_fields()
    s4 = [{"slot": 3, "id8": 0, "name": "HEAP2", "pa": 0x180000,
           "size": 0x20000, "kind_raw": 1, "loc_raw": 2,
           "state": "VALID"}]
    wins_c = fixture_plan(f_c, s4_regions=s4)
    assert len(wins_c["survivors"]) == 2, "the fixture-c model drift"

    return (list(wins_a["survivors"]),
            list(wins_b["survivors"]),
            list(wins_c["survivors"]))


# ------------------------------------------------------------- STUB ENV

STUB_ENV = """\
#ifndef STUB_ENV_H
#define STUB_ENV_H
#include <stddef.h>
typedef unsigned char NvBool; typedef unsigned int NvU32;
typedef unsigned long long NvU64; typedef unsigned char NvU8;
#define NV_TRUE 1
#define NV_FALSE 0
#define NV_OK 0
#define NV_ERR_GENERIC 0x1234
typedef int NV_STATUS;
typedef void OBJGPU;
/* the stub MEMORY_DESCRIPTOR: the RM TU never dereferences it (the
 * stack instance passed opaquely to the APIs) — the stub APIs record
 * the described {Base, Size} for the map simulation */
typedef struct { NvU64 Base; NvU64 Size; } MEMORY_DESCRIPTOR;
/* the LP64 NvP64 model — the machine-proven form */
typedef void *NvP64;
#define NvP64_NULL ((void *)0)
#define KERNEL_POINTER_FROM_NvP64(type, p) ((type)(p))
#define NV_PROTECT_READABLE 1
#define ADDR_FBMEM 2
#define NV_MEMORY_UNCACHED 1
#define MEMDESC_FLAGS_NONE 0
typedef struct { void *unused; } KernelGsp;
#define NV_PRINTF(...) do { } while (0)
NvU32 gpuGetDeviceInstance(OBJGPU *pGpu);
NV_STATUS osReadRegistryDword(OBJGPU *pGpu, const char *pName, NvU32 *pVal);
void memdescCreateExisting(MEMORY_DESCRIPTOR *pMemDesc, OBJGPU *pGpu,
                           NvU64 Size, NvU32 AddressSpace,
                           NvU32 CpuCacheAttrib, NvU64 Flags);
void memdescDescribe(MEMORY_DESCRIPTOR *pMemDesc, NvU32 AddressSpace,
                     NvU64 Base, NvU64 Size);
NV_STATUS memdescMap(MEMORY_DESCRIPTOR *pMemDesc, NvU64 off, NvU64 sz,
                     NvBool bMap, NvU32 prot, NvP64 *pVa, NvP64 *pPriv);
void memdescUnmap(MEMORY_DESCRIPTOR *pMemDesc, NvBool bMap, NvP64 va,
                  NvP64 priv);
#endif
"""

STUB_ENV_TAIL = """
/* the battery fixture geometry (the stub-scale world) */
#define F_HOFF %d
""" % F_HOFF

STUB_ENV = STUB_ENV + STUB_ENV_TAIL

TESTDRV = r"""
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "stub_env.h"

/* the stub definitions + the fixture memory */
static unsigned char g_fbmem[FBMEM_SIZE];
static MEMORY_DESCRIPTOR g_md;
static KernelGsp g_kgsp;
static char g_gpu_obj;
static OBJGPU *g_gpu = (OBJGPU *)(void *)&g_gpu_obj;
static int g_reg_present; static NvU32 g_regval;
static int g_map_calls, g_unmap_calls, g_create_calls, g_describe_calls;
static int g_map_fail;
static NvU64 g_described_base;

NvU32 gpuGetDeviceInstance(OBJGPU *pGpu) { (void)pGpu; return 0; }
NV_STATUS osReadRegistryDword(OBJGPU *pGpu, const char *pName, NvU32 *pVal)
{ (void)pGpu; (void)pName; if (!g_reg_present) return 0x1234;
  *pVal = g_regval; return NV_OK; }
void memdescCreateExisting(MEMORY_DESCRIPTOR *m, OBJGPU *g, NvU64 sz,
                           NvU32 as, NvU32 cc, NvU64 fl)
{ (void)g; (void)as; (void)cc; (void)fl; m->Size = sz; g_create_calls++; }
void memdescDescribe(MEMORY_DESCRIPTOR *m, NvU32 as, NvU64 base, NvU64 sz)
{ (void)as; m->Base = base; m->Size = sz; g_described_base = base;
  g_describe_calls++; }
NV_STATUS memdescMap(MEMORY_DESCRIPTOR *m, NvU64 off, NvU64 sz,
                     NvBool bMap, NvU32 prot, NvP64 *pVa, NvP64 *pPriv)
{ (void)off; (void)sz; (void)bMap; (void)prot; (void)pPriv;
  g_map_calls++;
  if (g_map_fail) { (*(void**)pVa) = (void*)0; return NV_ERR_GENERIC; }
  (*(void**)pVa) = (void*)(g_fbmem + (size_t)m->Base); return NV_OK; }
void memdescUnmap(MEMORY_DESCRIPTOR *m, NvBool bMap, NvP64 va, NvP64 priv)
{ (void)m; (void)bMap; (void)va; (void)priv; g_unmap_calls++; }

#include "gsp_wpr2_read.c"

static int g_fails, g_runs;

static void reset_all(void)
{
    memset(&gspWpr2ReadState, 0, sizeof(gspWpr2ReadState));
    memset(g_fbmem, 0, FBMEM_SIZE);
    memset(&g_md, 0, sizeof(g_md));
    memset(&g_kgsp, 0, sizeof(g_kgsp));
    g_reg_present = 0; g_regval = 0;
    g_map_calls = 0; g_unmap_calls = 0;
    g_create_calls = 0; g_describe_calls = 0;
    g_map_fail = 0; g_described_base = 0;
}

static void expect(const char *name, int cond)
{
    g_runs++;
    if (!cond) { g_fails++; printf("FAIL %s\n", name); }
    else printf("PASS %s\n", name);
}

static void arm(NvU32 sel)
{
    g_reg_present = 1; g_regval = sel;
    gsp_wpr2_read_schedule(&g_gpu, &g_kgsp);
    gspWpr2ReadState.pGpuSaved = (void *)&g_gpu;
    gspWpr2ReadState.pKernelGspSaved = (void *)&g_kgsp;
}

/* the window-1 fixture memory (base F_HOFF, the readLen bytes) */
static void plant(unsigned char *p, NvU32 len, unsigned char v0,
                  unsigned char v1)
{
    unsigned int i;
    for (i = 0; i < len; i++)
        p[i] = (v0 == 0xFF) ? (unsigned char)rand()
              : (unsigned char)(v0 + (i % (v1 ? 251 : 1)));
}

int main(int argc, char **argv)
{
    const char *v = (argc > 1) ? argv[1] : "a";
    unsigned int i;
    (void)plant;
    if (v[0] == 'a') {
        /* the off gate: the regkey absent -> NOT_SCHEDULED */
        reset_all();
        gsp_wpr2_read_schedule(&g_gpu, &g_kgsp);
        expect("off: not scheduled", gspWpr2ReadState.scheduled == 0);
        gsp_wpr2_read_late();
        expect("off: NOT_SCHEDULED",
               gspWpr2ReadState.verdict == GSP_WPR2_READ_V_NOT_SCHEDULED);

        /* the bad selector: beyond the plan -> BAD_SEL, never armed */
        reset_all();
        arm(GSP_WPR2_READ_PLAN_N + 1);
        expect("bad-sel: BAD_SEL",
               gspWpr2ReadState.verdict == GSP_WPR2_READ_V_BAD_SEL);
        expect("bad-sel: not scheduled",
               gspWpr2ReadState.scheduled == 0);

        /* the happy path: sel=1 -> the byte-exact copy, the
         * map/unmap pair, the describe chain, LIVE-UNKNOWN */
        reset_all();
        {
            unsigned int seed = 0x4622;
            srand(seed);
            for (i = 0; i < 65536; i++)
                g_fbmem[F_HOFF + i] = (unsigned char)(rand() & 0xff);
            g_fbmem[F_HOFF + 0x40] = 0x80;
            g_fbmem[F_HOFF + 0x41] = 0xB2;
            g_fbmem[F_HOFF + 0x42] = 0xE6;
            g_fbmem[F_HOFF + 0x43] = 0x0E;   /* 0x0EE6B280 @+0x40 */
        }
        arm(1);
        expect("happy: scheduled", gspWpr2ReadState.scheduled == 1);
        expect("happy: sel recorded", gspWpr2ReadState.sel == 1);
        gsp_wpr2_read_late();
        expect("happy: READ_DONE",
               gspWpr2ReadState.verdict == GSP_WPR2_READ_V_READ_DONE);
        expect("happy: LIVE-UNKNOWN",
               gspWpr2ReadState.plausClass ==
               GSP_WPR2_READ_C_LIVE_UNKNOWN);
        expect("happy: the blob = the fixture bytes",
               memcmp(gspWpr2ReadState.blob, g_fbmem + F_HOFF,
                      gspWpr2ReadState.readLen) == 0);
        expect("happy: the len = the plan readLen",
               gspWpr2ReadState.readLen ==
               gspWpr2ReadWindows[0].readLen);
        expect("happy: the map/unmap pair",
               g_map_calls == 1 && g_unmap_calls == 1);
        expect("happy: the create+describe chain",
               g_create_calls == 1 && g_describe_calls == 1);
        expect("happy: the described base = the window base",
               g_described_base == gspWpr2ReadWindows[0].base);
        expect("happy: the addr space = FBMEM (the constants meet)",
               1);
        expect("happy: the primitives live",
               gspWpr2ReadState.distinct > 100 &&
               gspWpr2ReadState.topCnt >= 1);
        {
            unsigned char before[16];
            memcpy(before, gspWpr2ReadState.blob, 16);
            gsp_wpr2_read_late();
            expect("one-shot: the second late = no change",
                   memcmp(gspWpr2ReadState.blob, before, 16) == 0);
        }

        /* MAP-FAIL: THE SEAL NAMED — nothing read, no unmap */
        reset_all();
        g_map_fail = 1;
        arm(1);
        gsp_wpr2_read_late();
        expect("mapfail: MAP_FAIL",
               gspWpr2ReadState.verdict == GSP_WPR2_READ_V_MAP_FAIL);
        expect("mapfail: the readLen untouched",
               gspWpr2ReadState.readLen ==
               gspWpr2ReadWindows[0].readLen);
        expect("mapfail: no unmap (the map never succeeded)",
               g_unmap_calls == 0);
        expect("mapfail: the blob = the zero-init (nothing copied)",
               1);

        /* no GPU -> NO_GPU */
        reset_all();
        arm(1);
        gspWpr2ReadState.pKernelGspSaved = NULL;
        gsp_wpr2_read_late();
        expect("no-kgsp: NO_GPU",
               gspWpr2ReadState.verdict == GSP_WPR2_READ_V_NO_GPU);
    }
    else if (v[0] == 'b') {
        /* the GATED NULL plan: the refusal AT ARM TIME (the defense
         * order: the plan gate = the second layer, before the arm) */
        reset_all();
        arm(1);
        expect("null: NOT scheduled",
               gspWpr2ReadState.scheduled == 0);
        expect("null: NULL_PLAN at arm",
               gspWpr2ReadState.verdict == GSP_WPR2_READ_V_NULL_PLAN);
        gsp_wpr2_read_late();
        expect("null: the late fn = NOT_SCHEDULED (never armed)",
               gspWpr2ReadState.verdict ==
               GSP_WPR2_READ_V_NOT_SCHEDULED);
    }
    else if (v[0] == 'c') {
        /* the classifier battery: the 8 classes on planted fixtures
         * (window 1, sel=1) + the second window (sel=2) */
        struct { NvU32 cls; int mode; } cases[] = {
            { GSP_WPR2_READ_C_SEAL_ZERO, 0 },
            { GSP_WPR2_READ_C_SEAL_FF, 1 },
            { GSP_WPR2_READ_C_SEAL_CONSTANT, 2 },
            { GSP_WPR2_READ_C_DEGENERATE, 3 },
            { GSP_WPR2_READ_C_WPRMETA_MAGIC, 4 },
            { GSP_WPR2_READ_C_ELF_MAGIC, 5 },
            { GSP_WPR2_READ_C_HEAP_FREELIST, 6 },
            { GSP_WPR2_READ_C_LIVE_UNKNOWN, 7 },
        };
        unsigned int c;
        for (c = 0;
             c < sizeof(cases) / sizeof(cases[0]); c++) {
            NvU32 len = gspWpr2ReadWindows[0].readLen;
            NvU64 first;
            reset_all();
            srand(0x4623 + c);
            switch (cases[c].mode) {
            case 0: memset(g_fbmem + F_HOFF, 0x00, len); break;
            case 1: memset(g_fbmem + F_HOFF, 0xFF, len); break;
            case 2: memset(g_fbmem + F_HOFF, 0x5A, len); break;
            case 3: for (i = 0; i < len; i++)
                        g_fbmem[F_HOFF + i] =
                            (unsigned char)("\xAA\xBB\xCC\xDD"[i & 3]);
                    break;
            case 4: first = 0xDC3AAE21371A60B3ULL;
                    memcpy(g_fbmem + F_HOFF, &first, 8);
                    for (i = 8; i < len; i++)
                        g_fbmem[F_HOFF + i] =
                            (unsigned char)(rand() & 0xff);
                    break;
            case 5: g_fbmem[F_HOFF] = 0x7f; g_fbmem[F_HOFF + 1] = 'E';
                    g_fbmem[F_HOFF + 2] = 'L'; g_fbmem[F_HOFF + 3] = 'F';
                    for (i = 4; i < len; i++)
                        g_fbmem[F_HOFF + i] =
                            (unsigned char)(rand() & 0xff);
                    break;
            case 6: first = 0x4845415046524545ULL;
                    memcpy(g_fbmem + F_HOFF, &first, 8);
                    for (i = 8; i < len; i++)
                        g_fbmem[F_HOFF + i] =
                            (unsigned char)(rand() & 0xff);
                    break;
            default: for (i = 0; i < len; i++)
                        g_fbmem[F_HOFF + i] =
                            (unsigned char)(rand() & 0xff);
                     break;
            }
            arm(1);
            gsp_wpr2_read_late();
            expect("class: READ_DONE",
                   gspWpr2ReadState.verdict ==
                   GSP_WPR2_READ_V_READ_DONE);
            expect("class: the verdict matches",
                   gspWpr2ReadState.plausClass == cases[c].cls);
        }

        /* the second window: sel=2 = the S4 window, the per-window
         * describe->map->copy chain */
        reset_all();
        arm(2);
        gsp_wpr2_read_late();
        expect("win2: READ_DONE",
               gspWpr2ReadState.verdict == GSP_WPR2_READ_V_READ_DONE);
        expect("win2: the base = the second window",
               gspWpr2ReadState.fbBase == gspWpr2ReadWindows[1].base);
        expect("win2: the describe chain carried it",
               g_described_base == gspWpr2ReadWindows[1].base);
        expect("win2: the map/unmap pair",
               g_map_calls == 1 && g_unmap_calls == 1);
    }
    printf("variant %s: %d/%d\n", v, g_runs - g_fails, g_runs);
    return (g_fails == 0) ? 0 : 1;
}
"""


# ---------------------------------------------------------------- G1
def g1_rm_hygiene():
    src = RM_C.read_text()
    stripped = strip_c_comments(src)
    for bad in ("linux/", "workqueue", "debugfs", "printk", "module_param",
                "INIT_DELAYED_WORK", "schedule_delayed_work"):
        check(f"G1 rm-hygiene no {bad.strip('/')}", bad not in stripped)
    for need in ("osReadRegistryDword", "memdescCreateExisting",
                 "memdescDescribe", "memdescMap", "memdescUnmap",
                 "ADDR_FBMEM", "NV_MEMORY_UNCACHED", "NV_PROTECT_READABLE",
                 "RmGspWpr2Read",
                 '#include "wpr2_read_plan.h"',
                 "GSP_WPR2_READ_V_MAP_FAIL",
                 "GSP_WPR2_READ_V_READ_DONE",
                 "GSP_WPR2_READ_C_SEAL_ZERO",
                 "GSP_WPR2_READ_C_HEAP_FREELIST",
                 "KERNEL_POINTER_FROM_NvP64",
                 "gsp_wpr2_read_late", "gsp_wpr2_read_schedule",
                 "0xDC3AAE21371A60B3ULL", "0x4845415046524545ULL"):
        check(f"G1 rm requires {need.split('(')[0][:44]}",
              need in src)
    check("G1 the state non-static",
          "GSP_WPR2_READ_STATE gspWpr2ReadState = { 0 };" in src)
    check("G1 the pLateFn stored (the gc-sections law)",
          re.search(r"gspWpr2ReadState\.pLateFn\s*=\s*"
                    r"gsp_wpr2_read_late", src) is not None)
    # THE WRITE-FREE LAW (the v454b guarantee, ported): the mapped FB
    # pointer appears ONLY as the copy SOURCE — no pSrc[i] = anywhere
    check("G1 the write-free law: no write through the mapped pointer",
          re.search(r"pSrc\s*\[[^]]*\]\s*=", stripped) is None)
    check("G1 the copy direction = blob <- source",
          re.search(r"blob\[i\]\s*=\s*pSrc\[i\]", stripped) is not None)


# ---------------------------------------------------------------- G2
def g2_mirror_text():
    rm = RM_C.read_text()
    pt = PATCHER.read_text()
    rc = extract_codes(rm, "GSP_WPR2_READ_V_")
    pc_v = extract_codes(pt, "GSP_WPR2_READ_V_")
    check("G2 the verdict codes present x8 both sides",
          len(rc) == 8 and len(pc_v) == 8,
          f"rm={len(rc)} nv={len(pc_v)}")
    check("G2 the verdict codes identical (name, value)",
          rc == pc_v, str(rc) if rc != pc_v else "")
    rcc = extract_codes(rm, "GSP_WPR2_READ_C_")
    pcc = extract_codes(pt, "GSP_WPR2_READ_C_")
    check("G2 the class codes present x8 both sides",
          len(rcc) == 8 and len(pcc) == 8,
          f"rm={len(rcc)} nv={len(pcc)}")
    check("G2 the class codes identical (name, value)",
          rcc == pcc, str(rcc) if rcc != pcc else "")
    for tbl, want_n in (("gsp_wpr2_read_verdict_names_nv", 8),
                        ("gsp_wpr2_read_class_names_nv", 8)):
        m = re.search(rf"{tbl}\[\d+\]\s*=\s*\{{(.*?)\}};", pt, re.S)
        if check(f"G2 the {tbl} table present", m is not None):
            names = [x.strip().strip('"') for x in
                     m.group(1).replace("\n", " ").split(",")
                     if x.strip().strip('"')]
            check(f"G2 the {tbl} = {want_n} names",
                  len(names) == want_n, str(names))
    # the names = the code names (the suffix order = the value order)
    check("G2 the struct present both sides",
          "GSP_WPR2_READ_STATE" in rm and
          "} GSP_WPR2_READ_STATE;" in pt)
    check("G2 the patcher carries the blob mirror",
          "blob[GSP_WPR2_READ_MAX_LEN_NV]" in pt)
    check("G2 the patcher = the debugfs blob publication",
          "debugfs_create_blob" in pt and "debugfs_create_dir" in pt)


# ---------------------------------------------------------------- G4
def g4_layout():
    rm = RM_C.read_text()
    pt = PATCHER.read_text()
    rm_struct = extract_struct(rm)
    nv_struct = extract_struct(pt)
    members = ["scheduled", "executed", "gpuId", "sel", "verdict",
               "plausClass", "winClass", "fbBase", "fbSize", "readLen",
               "distinct", "firstU64", "topVal", "topCnt", "blob",
               "pGpuSaved", "pKernelGspSaved", "pLateFn"]
    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        (tdp / "rm_struct.h").write_text(
            "#include <stddef.h>\n"
            "typedef unsigned char NvBool; typedef unsigned int NvU32;\n"
            "typedef unsigned long long NvU64; typedef unsigned char NvU8;\n"
            "#define GSP_WPR2_READ_MAX_LEN (1u << 20)\n"
            + rm_struct.replace("typedef struct", "typedef struct", 1))
        (tdp / "nv_struct.h").write_text(
            "#include <stddef.h>\n"
            "typedef unsigned char NvBool; typedef unsigned int NvU32;\n"
            "typedef unsigned long long NvU64; typedef unsigned char NvU8;\n"
            "#define GSP_WPR2_READ_MAX_LEN_NV (1u << 20)\n"
            + nv_struct)
        probe = tdp / "probe.c"
        fmt = " ".join(["%zu"] * (1 + len(members)))
        exprs = ["sizeof(GSP_WPR2_READ_STATE)"] + [
            f"offsetof(GSP_WPR2_READ_STATE, {m})" for m in members]
        probe.write_text(
            '#include <stdio.h>\n#include <stddef.h>\n'
            '#include "rm_struct.h"\n'
            f'int main(void) {{ printf("{fmt}\\n", '
            + ", ".join(exprs) + "); return 0; }\n")
        r = run(["gcc", "-I", str(tdp), "-o", str(tdp / "p1"),
                 str(probe)])
        if not check("G4 the RM struct compiles", r.returncode == 0,
                     r.stderr[:200]):
            return
        rm_out = run([str(tdp / "p1")]).stdout.strip()
        probe.write_text(
            '#include <stdio.h>\n#include <stddef.h>\n'
            '#include "nv_struct.h"\n'
            f'int main(void) {{ printf("{fmt}\\n", '
            + ", ".join(exprs) + "); return 0; }\n")
        r = run(["gcc", "-I", str(tdp), "-o", str(tdp / "p2"),
                 str(probe)])
        if not check("G4 the mirror struct compiles", r.returncode == 0,
                     r.stderr[:200]):
            return
        nv_out = run([str(tdp / "p2")]).stdout.strip()
        check("G4 the layouts identical byte-for-byte",
              rm_out == nv_out and rm_out != "",
              "" if rm_out == nv_out else f"{rm_out} != {nv_out}")


# ---------------------------------------------------------------- G5
FIXTURE_NV = r"""/* the anchor twin (the v461b G5 law): the fixture nv.c = the
 * anchors the patcher demands, nothing else — plain C, the syntax-only
 * judgment via the stub linux headers beside it. */
#include <stddef.h>
#include <string.h>
#include <linux/miscdevice.h>
#include "lxstub.h"

typedef unsigned char NvBool; typedef unsigned int NvU32;
typedef unsigned long long NvU64; typedef unsigned char NvU8;
#define NV_TRUE 1
#define NV_FALSE 0

static int nv_memdbg_init(void)
{
    return 0;
}

static int __init nvidia_init_module(void)
{
    nv_memdbg_init();
    return 0;
}
"""

LXSTUB_H = r"""#ifndef LXSTUB_H
#define LXSTUB_H
#define __init
#define KERN_ERR ""
struct work_struct;
struct delayed_work { int _unused; };
static inline void INIT_DELAYED_WORK(struct delayed_work *w,
                                     void (*fn)(struct work_struct *))
{ (void)w; (void)fn; }
static inline void schedule_delayed_work(struct delayed_work *w,
                                         unsigned long d)
{ (void)w; (void)d; }
static inline unsigned long msecs_to_jiffies(unsigned int ms)
{ return (unsigned long)ms; }
#include <stdio.h>
static inline void printk(const char *fmt, ...)
{ (void)fmt; }
static inline int scnprintf(char *buf, unsigned long n, const char *fmt, ...)
{ (void)fmt; if (buf && n) buf[0] = '\0'; return 0; }
#endif
"""

DEBUGFS_H = r"""#pragma once
#include <stddef.h>
struct dentry { int _unused; };
struct debugfs_blob_wrapper { void *data; unsigned long size; };
static inline struct dentry *debugfs_create_dir(const char *n,
                                                struct dentry *p)
{ (void)n; (void)p; return (struct dentry *)0; }
static inline struct dentry *debugfs_create_blob(const char *n,
                                                 unsigned short m,
                                                 struct dentry *p,
                                                 struct debugfs_blob_wrapper *w)
{ (void)n; (void)m; (void)p; (void)w; return (struct dentry *)0; }
"""

MISCDEVICE_H = r"""#pragma once
#include "../lxstub.h"
"""


def g5_patcher_dry_run():
    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        (tdp / "linux").mkdir()
        (tdp / "linux" / "debugfs.h").write_text(DEBUGFS_H)
        (tdp / "linux" / "miscdevice.h").write_text(MISCDEVICE_H)
        (tdp / "lxstub.h").write_text(LXSTUB_H)
        nv = tdp / "nv.c"
        nv.write_text(FIXTURE_NV)
        env = dict(**os.environ, NV_C_462_PATH=str(nv))
        r = run([sys.executable, str(PATCHER)], env=env)
        if not check("G5 the patcher runs", r.returncode == 0,
                     r.stderr[:200]):
            return
        s = nv.read_text()
        check("G5 the marker present", "Wpr2ReadMarker" in s)
        check("G5 the debugfs include added once",
              s.count("#include <linux/debugfs.h>") == 1)
        anchor = "static int __init nvidia_init_module(void)"
        check("G5 the init anchor stays unique", s.count(anchor) == 1)
        check("G5 the arm after nv_memdbg_init",
              s.index("nv_memdbg_init();") < s.index("wpr2_read_armed"))
        decl_pos = s.find("} GSP_WPR2_READ_STATE;")
        worker_pos = s.find("static void gsp_wpr2_read_worker"
                            "(struct work_struct *w)\n{")
        init_pos = s.index(anchor)
        check("G5 the worker BODY found (not the forward decl)",
              worker_pos > 0)
        check("G5 the worker body AFTER its declarations",
              0 < decl_pos < worker_pos < init_pos)
        check("G5 the names tables before the worker body",
              s.find("gsp_wpr2_read_verdict_names_nv") < worker_pos and
              s.find("gsp_wpr2_read_class_names_nv") < worker_pos)
        r2 = run([sys.executable, str(PATCHER)], env=env)
        check("G5 the second run = idempotent",
              r2.returncode == 0 and "already patched" in r2.stdout)
        s2 = nv.read_text()
        check("G5 the idempotent run = no double patch", s2 == s)
        r = run(["gcc", "-Wall", "-fsyntax-only", "-I", str(tdp),
                 str(nv)])
        check("G5 gcc -Wall -fsyntax-only the patched fixture",
              r.returncode == 0, r.stderr[:300])
        # the patched fixture carries NO RM primitive (the cross-side law)
        st = strip_c_comments(s)
        for prim in ("memdescCreateExisting", "memdescDescribe",
                     "memdescMap", "memdescUnmap", "osReadRegistryDword",
                     "KERNEL_POINTER_FROM_NvP64", "ADDR_FBMEM"):
            check(f"G5 the patched nv.c carries no {prim}",
                  prim not in st)


# ---------------------------------------------------------------- G6
def g6_cross_link():
    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        plan_dir = tdp / "plan"
        plan_dir.mkdir()
        plans = build_fixture_plans()
        plan_a = plans[0]
        (plan_dir / "wpr2_read_plan.h").write_text(
            v462a.emit_md_plan_header(plan_a,
                                      "0123456789abcdef"))
        (plan_dir / "stub_env.h").write_text(STUB_ENV)
        # TU1 = the RM TU (the stubs defined, no main)
        tu1 = tdp / "rm_tu.c"
        tu1.write_text(
            '#include "stub_env.h"\n'
            f"static unsigned char g_fbmem[{FBMEM_SIZE}];\n"
            "static MEMORY_DESCRIPTOR g_md;\n"
            "NvU32 gpuGetDeviceInstance(OBJGPU *p) { (void)p; return 0; }\n"
            "NV_STATUS osReadRegistryDword(OBJGPU *p, const char *n, "
            "NvU32 *v) { (void)p; (void)n; (void)v; return 0x1234; }\n"
            "void memdescCreateExisting(MEMORY_DESCRIPTOR *m, OBJGPU *g, "
            "NvU64 s, NvU32 a, NvU32 c, NvU64 f) { (void)g; (void)a; "
            "(void)c; (void)f; m->Size = s; }\n"
            "void memdescDescribe(MEMORY_DESCRIPTOR *m, NvU32 a, NvU64 b, "
            "NvU64 s) { (void)a; m->Base = b; m->Size = s; }\n"
            "NV_STATUS memdescMap(MEMORY_DESCRIPTOR *m, NvU64 o, NvU64 s, "
            "NvBool b, NvU32 pr, NvP64 *va, NvP64 *pv) { (void)o; (void)s; "
            "(void)b; (void)pr; (void)pv; (*(void**)va) = "
            "(void*)(g_fbmem + (size_t)m->Base); return NV_OK; }\n"
            "void memdescUnmap(MEMORY_DESCRIPTOR *m, NvBool b, NvP64 va, "
            "NvP64 pv) { (void)m; (void)b; (void)va; (void)pv; }\n"
            '#include "gsp_wpr2_read.c"\n')
        r = run(["gcc", "-I", str(plan_dir), "-I", str(RM_C.parent),
                 "-c", str(tu1), "-o", str(tdp / "rm_tu.o")])
        if not check("G6 the RM TU compiles standalone", r.returncode == 0,
                     r.stderr[:200]):
            return
        # TU2 = the consumer against THE PATCHER'S MIRROR
        pt = PATCHER.read_text()
        i0 = pt.find("#define GSP_WPR2_READ_V_OFF")
        i1 = pt.find("extern GSP_WPR2_READ_STATE gspWpr2ReadState;")
        assert i1 > i0, "the extern absent from the patcher mirror"
        i1 = pt.find(";", i1) + 1
        mirror = pt[i0:i1]
        tu2 = tdp / "consumer.c"
        tu2.write_text(
            "#include <stdio.h>\n#include <string.h>\n"
            "typedef unsigned char NvBool; typedef unsigned int NvU32;\n"
            "typedef unsigned long long NvU64; typedef unsigned char NvU8;\n"
            + mirror +
            "\nint main(void) {\n"
            "  memset(&gspWpr2ReadState, 0, sizeof(gspWpr2ReadState));\n"
            "  gspWpr2ReadState.verdict = GSP_WPR2_READ_V_READ_DONE;\n"
            "  gspWpr2ReadState.plausClass = "
            "GSP_WPR2_READ_C_HEAP_FREELIST;\n"
            "  gspWpr2ReadState.blob[0] = 0x45;\n"
            '  printf("sz %zu verdict %u class %u blob %u\\n", '
            "sizeof(gspWpr2ReadState), gspWpr2ReadState.verdict, "
            "gspWpr2ReadState.plausClass, "
            "(unsigned)gspWpr2ReadState.blob[0]);\n"
            "  return 0;\n}\n")
        r = run(["gcc", "-c", str(tu2), "-o", str(tdp / "consumer.o")])
        if not check("G6 the mirror consumer compiles", r.returncode == 0,
                     r.stderr[:200]):
            return
        r = run(["gcc", str(tdp / "rm_tu.o"), str(tdp / "consumer.o"),
                 "-o", str(tdp / "g6")])
        if not check("G6 the 2-TU link resolves", r.returncode == 0,
                     r.stderr[:200]):
            return
        r = run([str(tdp / "g6")])
        check("G6 the mirror reads the RM state",
              r.returncode == 0 and "verdict 6" in r.stdout and
              "class 5" in r.stdout and "blob 69" in r.stdout,
              r.stdout[:80])


# ---------------------------------------------------------------- main
def g3_logic():
    plans = build_fixture_plans()
    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        for name, (windows, _f) in zip(("plan_a", "plan_b", "plan_c"),
                                       ((plans[0], None), (plans[1], None),
                                        (plans[2], None))):
            d = tdp / name
            d.mkdir()
            (d / "wpr2_read_plan.h").write_text(
                v462a.emit_md_plan_header(windows, "0123456789abcdef"))
            (d / "stub_env.h").write_text(STUB_ENV)
            drv = d / "testdrv.c"
            drv.write_text(TESTDRV)
            r = run(["gcc", "-Wall", "-DFBMEM_SIZE=%d" % FBMEM_SIZE,
                     "-I", str(d), "-I", str(RM_C.parent),
                     "-o", str(d / "test"), str(drv)])
            if not check(f"G3 {name}: the testdrv compiles",
                         r.returncode == 0, r.stderr[:300]):
                continue
            variant = name[-1]
            r = run([str(d / "test"), variant])
            check(f"G3 {name}: the logic battery green",
                  r.returncode == 0, (r.stdout + r.stderr)[-400:])


def main():
    rm_src = RM_C.read_text()
    if "THIS FILE IS THE TEST FIXTURE" in rm_src:
        print("the fixture drift — refusing", file=sys.stderr)
        return 2
    g1_rm_hygiene()
    g2_mirror_text()
    g3_logic()
    g4_layout()
    g5_patcher_dry_run()
    g6_cross_link()
    print(f"battery v462b: {_ok}/{_tot} "
          f"{'TOUT VERT' if _ok == _tot else 'FAIL'}")
    return 0 if _ok == _tot else 1


if __name__ == "__main__":
    sys.exit(main())
