// gsp_hpoke.c — PASS 4.52 T3 — the route-H heap-poke writer (v2).
//
// The 4.52 brief: the writer GATÉ par une clé séparée (RmGspHPoke=1),
// UN champ par boot, le pre/post-verify imprimé en dmesg, l'ancre
// memdescMap WRITEABLE déjà prouvée dans l'arbre (kernel_gsp.c ~6028,
// the kgspCreateRadix3 map pattern), le builder C byte-exact testé vs
// python (the v452c --emit-c --test-c battery, the 4.44 lesson), le
// runbook-452 gaté comme le 445.
//
// GROUNDING (the EXACT tree, open-gpu-kernel-modules @ 610.57.04):
//   - kernel_gsp.c:6028  memdescMap(*ppMemdescRadix3, 0, allocSize,
//     NV_TRUE, NV_PROTECT_WRITEABLE, &pVaKernel, &pPrivKernel) — the
//     PROVEN kernel-map pattern this file reuses on the sysmem heap;
//   - kernel_gsp_tu102.c:214  pSysmemHeapDescriptor = a CONTIGUOUS
//     UNCACHED SYSMEM alloc (heapSizeMB << 20) — UNCACHED means the
//     CPU write is coherent with the GSP's PCIe/CE reads (no stale
//     CPU-cache question on the surface);
//   - kernel_gsp.c:312  osReadRegistryDword — the regkey pattern the
//     4.51 instrument banked (gsp_dmem_dump.c uses the same call);
//   - kernel_gsp.c ~4033  the 4-arg memdescUnmap pattern (the state-
//     monitor map teardown, banked 4.51);
//   - v451b_timing_targets.json route H: "the surface is host-writable
//     RAM by construction, post-verify by construction".
//
// THE GATE (the 4.52 brief, verbatim): the key = RmGspHPoke, SEPARATE
// from the 4.51 dump key. The VALUE selects THE ONE field:
//     NVreg_RegistryDwords="RmGspHPoke=1"   -> sel 1 = rc
//     RmGspHPoke=2                          -> sel 2 = rfc
//     (3 = ras, 4 = faw, 5 = rrd — the SELECTORS map of v452c)
//     absent / 0 / out-of-range            -> OFF (or the dmesg refusal)
// UN FIELD PAR BOOT: the work applies THE ONE matching plan entry —
// no loop, no batch, no retry. The next field = the next boot (the
// TIER 2 doctrine: one variable per transition).
//
// THE PLAN (gsp_hpoke_plan.h) is GENERATED by v452c_hpatch_build.py:
// the offsets/old/new bytes = the v452b candidates (the runtime truth
// + the v451b LHR values). plan_sha16 binds the compiled table to the
// reviewed plan; the dmesg prints it NEXT TO the verify results — any
// drift is visible in the boot ledger. A NULL plan (no eligible
// candidate) makes every write request refuse cleanly.
//
// THE ORDER OF DEFENSE (each layer independent):
//   1. the regkey gate (absent/0 = the file does nothing);
//   2. the selector filter (ONE entry; the others are never touched);
//   3. the PRE-VERIFY: the runtime bytes must equal the plan's old
//      bytes — a moved/rewritten record (or the id-19 all-zero
//      landmine) aborts BEFORE any write (the STALE-PLAN verdict);
//   4. the write (byte-lane width only);
//   5. the POST-VERIFY: the readback must equal the new bytes (the
//      VERIFY-FAIL verdict is printed, never retried, never hidden);
//   6. the dmesg ledger for every verdict (the nv_printf lesson).
//
// INTEGRATION (kernel_gsp.c, the ONE hook line — next to the 4.51
// instrument's, same anchor, the success path after the log polling):
//     NV_CHECK_OK_OR_GOTO(status, LEVEL_ERROR, kgspStartLogPolling(pGpu, pKernelGsp), done);
//     gsp_dmem_dump_schedule(pGpu, pKernelGsp, pGspFw);   // (4.51, opt-in dump)
//     gsp_hpoke_schedule(pGpu, pKernelGsp);               // <-- INSERT THIS
// and near the top of kernel_gsp.c:  #include "gsp_hpoke.c"
// (the plan header lives beside it:  #include "gsp_hpoke_plan.h").
//
// ROLLBACK (runbook-452 §6): this file + the plan header + the ONE
// hook line = the ONLY changes; the restore = git checkout --
// src/nvidia/src/kernel/gpu/gsp/kernel_gsp.c + rm gsp_hpoke.c
// gsp_hpoke_plan.h + dkms + limine-mkinitcpio (the UKI lesson). The
// registry key removal = the conf edit (the runbook prints it). The
// firmware file is NEVER touched (the §0 sha guard).
//
// SAFETY: the write happens ONCE per boot, into the sysmem heap ONLY,
// at the offsets the reviewed plan carries, at the byte-lane width
// the scan proved. No MMIO write, no firmware file write, no falcon
// mailbox — the route-H surface is host-writable RAM by construction
// (the v451b route table). Do not unload the driver inside the 8 s
// window (the work holds the descriptor pointer; the runbook rollback
// = reboot into the reverted driver anyway).

// ---------------------------------------------------------------------------
// Included by kernel_gsp.c — reuses the translation unit's includes.
// ---------------------------------------------------------------------------
#include <linux/workqueue.h>

#include "gsp_hpoke_plan.h"   // GENERATED — the reviewed write plan

typedef struct
{
    NvBool     scheduled;
    NvU32      gpuId;
    NvU32      sel;      // the RmGspHPoke value THIS boot selected
    OBJGPU    *pGpu;
    KernelGsp *pKernelGsp;
} GSP_HPOKE_STATE;

static GSP_HPOKE_STATE _gspHpokeState = { 0 };

static void _gsp_hpoke_work(struct work_struct *pWork);
static DECLARE_DELAYED_WORK(_gspHpokeWork, _gsp_hpoke_work);

// the selector names (the v452c SELECTORS map) — the dmesg readability
static const char *_gspHpokeFieldName(NvU32 sel)
{
    switch (sel)
    {
        case 1: return "rc";
        case 2: return "rfc";
        case 3: return "ras";
        case 4: return "faw";
        case 5: return "rrd";
        default: return "?";
    }
}

static void
_gsp_hpoke_hex(const NvU8 *p, NvU32 len, char *out, NvU32 outLen)
{
    NvU32 i;
    NvU32 n = 0;
    for (i = 0; (i < len) && ((n + 3) < outLen); i++)
    {
        out[n++] = "0123456789abcdef"[p[i] >> 4];
        out[n++] = "0123456789abcdef"[p[i] & 0xf];
    }
    out[n] = '\0';
}

static void
_gsp_hpoke_work(struct work_struct *pWork)
{
    OBJGPU             *pGpu       = _gspHpokeState.pGpu;
    KernelGsp          *pKernelGsp = _gspHpokeState.pKernelGsp;
    const GSP_HPOKE_ENTRY *pEntry  = NULL;
    NvU32               sel        = _gspHpokeState.sel;
    NvU32               i;
    void               *pVa        = NULL;
    NvP64               pPriv      = NvP64_NULL;
    NvU64               sz;
    NV_STATUS           st;
    NvU8               *pHeap;

    if ((pGpu == NULL) || (pKernelGsp == NULL))
        return;
    if (pKernelGsp->pSysmemHeapDescriptor == NULL)
    {
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: no sysmem heap descriptor — "
                               "the poke refuses (nothing written)\n");
        return;
    }
    if ((GSP_HPOKE_PLAN_N == 0) || (gspHpokePlan[0].sel == 0))
    {
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: the plan is the GATED NULL "
                               "plan — no eligible candidate, nothing "
                               "to write (re-run v452b/v452c)\n");
        return;
    }

    // ---- the ONE entry for THIS boot (the selector filter) ----
    for (i = 0; i < GSP_HPOKE_PLAN_N; i++)
    {
        if (gspHpokePlan[i].sel == sel)
        {
            pEntry = &gspHpokePlan[i];
            break;
        }
    }
    if (pEntry == NULL)
    {
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: sel=%u (%s) not in the plan "
                               "(plan_sha16=%s) — nothing written\n",
                  sel, _gspHpokeFieldName(sel), GSP_HPOKE_PLAN_SHA16);
        return;
    }

    // ---- the map: the radix3 WRITEABLE pattern @kernel_gsp.c:6028 ----
    sz = pKernelGsp->pSysmemHeapDescriptor->Size;
    if (pEntry->heapOffset + pEntry->len > sz)
    {
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: plan offset 0x%llx beyond the "
                               "heap (0x%llx) — the plan is for another "
                               "heap size, nothing written\n",
                  pEntry->heapOffset, sz);
        return;
    }
    st = memdescMap(pKernelGsp->pSysmemHeapDescriptor, 0, sz,
                    NV_TRUE, NV_PROTECT_WRITEABLE,
                    (NvP64 *)&pVa, &pPriv);
    if ((st != NV_OK) || (pVa == NULL))
    {
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: the heap map FAILED st=0x%x — "
                               "nothing written\n", st);
        return;
    }
    pHeap = (NvU8 *)KERNEL_POINTER_FROM_NvP64(NvU8 *, pVa);

    // ---- the PRE-VERIFY: the runtime truth must match the plan ----
    {
        NvU8 oldSeen[8] = { 0 };
        char hexOld[32];
        char hexWant[32];

        for (i = 0; i < pEntry->len; i++)
            oldSeen[i] = pHeap[pEntry->heapOffset + i];
        _gsp_hpoke_hex(oldSeen, pEntry->len, hexOld, sizeof(hexOld));
        _gsp_hpoke_hex(pEntry->old, pEntry->len, hexWant, sizeof(hexWant));

        for (i = 0; i < pEntry->len; i++)
        {
            if (oldSeen[i] != pEntry->old[i])
            {
                NV_PRINTF(LEVEL_ERROR,
                          "NVRM-452: STALE-PLAN sel=%u (%s) off=0x%llx "
                          "seen=%s want=%s plan_sha16=%s — the runtime "
                          "moved (or the id-19 landmine) — ABORT, "
                          "nothing written\n",
                          sel, _gspHpokeFieldName(sel),
                          pEntry->heapOffset, hexOld, hexWant,
                          GSP_HPOKE_PLAN_SHA16);
                memdescUnmap(pKernelGsp->pSysmemHeapDescriptor, NV_TRUE,
                             pVa, pPriv);
                return;
            }
        }
        NV_PRINTF(LEVEL_INFO, "NVRM-452: pre-verify OK sel=%u (%s) "
                              "off=0x%llx seen=%s plan_sha16=%s\n",
                  sel, _gspHpokeFieldName(sel), pEntry->heapOffset,
                  hexOld, GSP_HPOKE_PLAN_SHA16);
    }

    // ---- the WRITE (byte-lane width, one field, no retry) ----
    for (i = 0; i < pEntry->len; i++)
        pHeap[pEntry->heapOffset + i] = pEntry->nw[i];

    // ---- the POST-VERIFY: the readback must equal the new bytes ----
    {
        NvU8 newSeen[8] = { 0 };
        NvBool ok = NV_TRUE;
        char hexNew[32];

        for (i = 0; i < pEntry->len; i++)
            newSeen[i] = pHeap[pEntry->heapOffset + i];
        for (i = 0; i < pEntry->len; i++)
            ok = ok && (newSeen[i] == pEntry->nw[i]);
        _gsp_hpoke_hex(newSeen, pEntry->len, hexNew, sizeof(hexNew));

        NV_PRINTF(ok ? LEVEL_INFO : LEVEL_ERROR,
                  "NVRM-452: poke sel=%u (%s) off=0x%llx new=%s "
                  "verify=%s plan_sha16=%s\n",
                  sel, _gspHpokeFieldName(sel), pEntry->heapOffset,
                  hexNew, ok ? "OK" : "FAIL", GSP_HPOKE_PLAN_SHA16);
    }

    // ---- the unmap (the 4-arg pattern, kernel_gsp.c ~4033) ----
    memdescUnmap(pKernelGsp->pSysmemHeapDescriptor, NV_TRUE, pVa, pPriv);
}

// ---- the scheduler (the hook target) ----

void
gsp_hpoke_schedule(OBJGPU *pGpu, KernelGsp *pKernelGsp)
{
    NvU32 sel = 0;

    if (osReadRegistryDword(pGpu, "RmGspHPoke", &sel) != NV_OK)
        sel = 0; // default OFF — the opt-in writer, SEPARATE from the
                 // 4.51 dump key (the two instruments coexist cleanly)
    if ((sel == 0) || (sel > 5))
    {
        if (sel > 5)
            NV_PRINTF(LEVEL_ERROR, "NVRM-452: RmGspHPoke=%u out of the "
                                   "selector domain {1..5} — OFF\n", sel);
        return;
    }

    if (_gspHpokeState.scheduled)
        return;
    _gspHpokeState.scheduled  = NV_TRUE;
    _gspHpokeState.pGpu       = pGpu;
    _gspHpokeState.pKernelGsp = pKernelGsp;
    _gspHpokeState.gpuId      = gpuGetDeviceInstance(pGpu);
    _gspHpokeState.sel        = sel;   // the dedicated member — the
                                       // work reads THE boot's selector
                                       // from it (never overload gpuId)

    schedule_delayed_work(&_gspHpokeWork, msecs_to_jiffies(8 * 1000));
    NV_PRINTF(LEVEL_INFO, "NVRM-452: gsp_hpoke scheduled (+8 s) sel=%u "
                          "(%s) ONE field this boot plan_sha16=%s\n",
              sel, _gspHpokeFieldName(sel), GSP_HPOKE_PLAN_SHA16);
}
