// gsp_hpoke.c — PASS 4.52 T3 (the route-H heap-poke writer, v2) —
// PASS 4.55: THE TWO-SIDED CONVERSION (the debt gsp_hpoke.c:79 paid).
//
// THE DEBT (findings-4.53 §6, the 3rd occurrence of the same trap): the
// v2 file carried `#include <linux/workqueue.h>` while being INCLUDED BY
// kernel_gsp.c — the RM TU = the OS-ABSTRACTED environment, ZERO linux
// headers (the port layer only). The identical fail killed the 4.51 v1
// monolith (the build = the judge, caught at the machine-day pre-flight)
// and was paid there by the TWO-SIDED pattern (gsp_dmem_dump.c +
// patch_nv_451.py) — the pattern this conversion replicates for the
// writer, verified end-to-end on the 4.51 machine day (4 boots, 0 Xid).
//
// THE TWO SIDES:
//   THIS file (the RM TU, included by kernel_gsp.c): the regkey gate
//     (osReadRegistryDword), the selector filter, the plan table
//     (gsp_hpoke_plan.h — the v452c-generated RM header), the radix3
//     WRITEABLE map, the PRE-VERIFY, the byte-lane write, the
//     POST-VERIFY, the unmap — ALL RM-portable primitives, ZERO linux
//     headers. The verdicts = recorded INTO the shared state (the
//     4.51 lesson: the RM NV_PRINTF = level-gated — the nv.c printk =
//     the reliable ledger). The late function = stored as a FUNCTION
//     POINTER in the state (the gc-sections law: the live schedule
//     stores the pointer, so it cannot be stripped; the nv.c side
//     calls THROUGH the pointer — NO cross-TU symbol at all).
//   the nv.c side (kernel-open/nvidia/nv.c, the linux TU): the delayed
//     work (INIT_DELAYED_WORK + schedule_delayed_work, 8 s) armed at
//     module init, the call through pLateFn, the printk LEDGER (every
//     verdict, from the state). = patch_nv_452.py (the v9-scanner
//     anchor pattern, idempotent HpokeMarker, coexists with the 4.51
//     DmemDumpMarker).
//
// GROUNDING (the EXACT tree, open-gpu-kernel-modules @ 610.57.04):
//   - kernel_gsp.c:6028  memdescMap(*ppMemdescRadix3, 0, allocSize,
//     NV_TRUE, NV_PROTECT_WRITEABLE, &pVaKernel, &pPrivKernel) — the
//     PROVEN kernel-map pattern this file reuses on the sysmem heap;
//   - kernel_gsp_tu102.c:214  pSysmemHeapDescriptor = a CONTIGUOUS
//     UNCACHED SYSMEM alloc (heapSizeMB << 20) — UNCACHED means the
//     CPU write is coherent with the GSP's PCIe/CE reads (no stale
//     CPU-cache question on the surface);
//   - kernel_gsp.c:312  osReadRegistryDword — the regkey pattern the
//     4.51 instrument banked (gsp_dmem_dump.c uses the same call);
//   - kernel_gsp.c ~4033  the 4-arg memdescUnmap pattern (the state-
//     monitor map teardown, banked 4.51);
//   - the pLateFn mechanics = gsp_dmem_dump.c v4 (the boot-B proof:
//     the descriptor = NULL at the hook, the late read at +8 s works).
//
// THE GATE (the 4.52 brief, verbatim, UNCHANGED): the key = RmGspHPoke,
// SEPARATE from the 4.51 dump key. The VALUE selects THE ONE field:
//     NVreg_RegistryDwords="RmGspHPoke=1"   -> sel 1 = rc
//     RmGspHPoke=2                          -> sel 2 = rfc
//     (3 = ras, 4 = faw, 5 = rrd — the SELECTORS map of v452c)
//     absent / 0 / out-of-range            -> OFF (the verdict recorded,
//                                             the nv.c ledger prints it)
// UN FIELD PAR BOOT: the late function applies THE ONE matching plan
// entry — no loop, no batch, no retry. The next field = the next boot
// (the TIER 2 doctrine: one variable per transition).
//
// THE PLAN (gsp_hpoke_plan.h) is GENERATED by v452c_hpatch_build.py:
// the offsets/old/new bytes = the v452b candidates (the runtime truth
// + the v451b LHR values). plan_sha16 binds the compiled table to the
// reviewed plan; the state carries a COPY of it — the nv.c ledger
// prints it NEXT TO the verify results — any drift is visible in the
// boot ledger. A NULL plan (no eligible candidate) makes every write
// request refuse cleanly.
//
// THE ORDER OF DEFENSE (each layer independent, UNCHANGED):
//   1. the regkey gate (absent/0 = the file does nothing);
//   2. the selector filter (ONE entry; the others are never touched);
//   3. the PRE-VERIFY: the runtime bytes must equal the plan's old
//      bytes — a moved/rewritten record (or the id-19 all-zero
//      landmine) aborts BEFORE any write (the STALE-PLAN verdict);
//   4. the write (byte-lane width only);
//   5. the POST-VERIFY: the readback must equal the new bytes (the
//      VERIFY-FAIL verdict is recorded, never retried, never hidden);
//   6. the ledger: the state verdicts -> the nv.c printk (the reliable
//      surface) + the RM NV_PRINTF kept (the RM-debug bonus, never the
//      reliance).
//
// THE SHARED STATE CONTRACT (the layout MIRROR lives in
// patch_nv_452.py — the v455a selftest compiles BOTH and asserts the
// sizeof/offsetof agreement member by member; the mirror drift = the
// build/lab fail, never the machine day):
//     scheduled/verdict/verifyOk/heapOffset/len/fieldName/hex*/sha16/
//     pGpuSaved/pKernelGspSaved/pLateFn/executed
//   The RM side WRITES it (the schedule + the late fn); the nv.c side
//   READS it (the ledger) and CALLS THROUGH pLateFn. Nothing else.
//
// INTEGRATION (kernel_gsp.c, the ONE hook line — UNCHANGED from 4.52,
// next to the 4.51 instrument's, same anchor, the success path after
// the log polling):
//     NV_CHECK_OK_OR_GOTO(status, LEVEL_ERROR, kgspStartLogPolling(pGpu, pKernelGsp), done);
//     gsp_dmem_dump_schedule(pGpu, pKernelGsp, pGspFw);   // (4.51, opt-in dump)
//     gsp_hpoke_schedule(pGpu, pKernelGsp);               // <-- INSERT THIS
// and near the top of kernel_gsp.c:  #include "gsp_hpoke.c"
// (the plan header lives beside it:  #include "gsp_hpoke_plan.h").
// BUILD DAY (the runbook-452 §4, the 4.55 addition): apply
// patch_nv_452.py to kernel-open/nvidia/nv.c BEFORE the dkms — without
// it the build still passes (the RM side is self-contained) but the
// late fn is never called (the silent no-op — the runbook now REFUSES
// on the missing HpokeMarker).
//
// ROLLBACK (runbook-452 §6): this file + the plan header + the ONE
// hook line + the nv.c patch (git checkout -- kernel-open/nvidia/nv.c)
// = the ONLY changes; the restore = git checkout --
// src/nvidia/src/kernel/gpu/gsp/kernel_gsp.c + rm gsp_hpoke.c
// gsp_hpoke_plan.h + dkms + limine-mkinitcpio (the UKI lesson). The
// registry key removal = the conf edit (the runbook prints it). The
// firmware file is NEVER touched (the §0 sha guard).
//
// SAFETY: the write happens ONCE per boot, into the sysmem heap ONLY,
// at the offsets the reviewed plan carries, at the byte-lane width
// the scan proved. No MMIO write, no firmware file write, no falcon
// mailbox — the route-H surface is host-writable RAM by construction
// (the v451b route table). Do not unload the driver inside the 8 s
// window (the work holds the descriptor pointer; the runbook rollback
// = reboot into the reverted driver anyway).

// ---------------------------------------------------------------------------
// Included by kernel_gsp.c — reuses the translation unit's includes.
// ZERO linux headers HERE (the 4.55 contract — the v455a selftest
// greps this file for linux/ workqueue/ debugfs/ printk and FAILS the
// battery if the trap ever returns).
// ---------------------------------------------------------------------------
#include "gsp_hpoke_plan.h"   // GENERATED — the reviewed write plan (RM header)

// the verdict codes — THE MIRROR CONTRACT (the nv.c side carries the
// SAME values; the names table lives on the nv.c side, the v455a
// selftest compares the two tables element by element)
#define GSP_HPOKE_V_OFF             0  // the regkey absent/0 — nothing to do
#define GSP_HPOKE_V_BAD_SEL         1  // the value outside {1..5}
#define GSP_HPOKE_V_NO_HEAP_DESC    2  // the descriptor NULL at +8 s
#define GSP_HPOKE_V_NULL_PLAN       3  // the GATED null plan compiled in
#define GSP_HPOKE_V_SEL_NOT_IN_PLAN 4  // the selector has no plan entry
#define GSP_HPOKE_V_BOUNDS          5  // the plan offset beyond the heap
#define GSP_HPOKE_V_MAP_FAIL        6  // the memdescMap failed
#define GSP_HPOKE_V_STALE_PLAN      7  // the pre-verify mismatch — ABORT
#define GSP_HPOKE_V_WRITE_DONE      8  // the write ran (verifyOk = the result)
#define GSP_HPOKE_V_NOT_SCHEDULED   9  // the late call with the gate off

typedef struct
{
    NvBool     scheduled;      // the regkey gate result (the hook ran + opted in)
    NvBool     executed;       // the one-shot guard on the late fn
    NvU32      gpuId;
    NvU32      sel;            // the RmGspHPoke value THIS boot selected
    NvU32      verdict;        // GSP_HPOKE_V_*
    NvU32      verifyOk;       // 1 = the post-verify matched (WRITE_DONE only)
    NvU64      heapOffset;     // the entry's offset (the ledger)
    NvU32      len;            // the byte-lane width (the ledger)
    char       fieldName[8];   // "rc"/"rfc"/... (the ledger readability)
    char       hexSeen[24];    // the pre-verify runtime bytes (rendered)
    char       hexWant[24];    // the plan old bytes (rendered)
    char       hexNew[24];     // the post-write bytes (rendered)
    char       sha16[20];      // the GSP_HPOKE_PLAN_SHA16 copy (17 max)
    void      *pGpuSaved;
    void      *pKernelGspSaved;
    void     (*pLateFn)(void); // the late poke, called BY POINTER (the
                              // gc-sections law — NO cross-TU symbol)
} GSP_HPOKE_STATE;

// non-static: the nv.c (kernel-open) side reads this for the ledger and
// calls through pLateFn (the 4.51 v4 pattern, machine-proven)
GSP_HPOKE_STATE gspHpokeState = { 0 };

void gsp_hpoke_late(void);   // the forward decl: the schedule stores the pointer below

static const char *
_gsp_hpoke_field_name(NvU32 sel)
{
    switch (sel)
    {
        case 1: return "rc";
        case 2: return "rfc";
        case 3: return "ras";
        case 4: return "faw";
        case 5: return "rrd";
        default: return "?";
    }
}

static void
_gsp_hpoke_hex(const NvU8 *p, NvU32 len, char *out, NvU32 outLen)
{
    NvU32 i;
    NvU32 n = 0;
    for (i = 0; (i < len) && ((n + 3) < outLen); i++)
    {
        out[n++] = "0123456789abcdef"[p[i] >> 4];
        out[n++] = "0123456789abcdef"[p[i] & 0xf];
    }
    out[n] = '\0';
}

// ---- the late poke (the old work body, RM-portable, verdicts recorded) ----
// Called BY POINTER (the state's pLateFn) from the nv.c delayed work at
// +8 s after module init — the descriptor = allocated by then (the boot-B
// proof). (The gc-sections = cannot strip it: the live schedule stores
// this function's pointer into the shared state.)

void
gsp_hpoke_late(void)
{
    KernelGsp             *pKernelGsp = (KernelGsp *)gspHpokeState.pKernelGspSaved;
    const GSP_HPOKE_ENTRY *pEntry     = NULL;
    NvU32                  sel        = gspHpokeState.sel;
    NvU32                  i;
    void                  *pVa        = NULL;
    NvP64                  pPriv      = NvP64_NULL;
    NvU64                  sz;
    NV_STATUS              st;
    NvU8                  *pHeap;

    // the one-shot + the gate guard (the double-late defense in depth)
    if (gspHpokeState.executed)
        return;
    if (!gspHpokeState.scheduled)
    {
        gspHpokeState.verdict = GSP_HPOKE_V_NOT_SCHEDULED;
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: the late poke with the gate off "
                               "(RmGspHPoke absent, or the hook never ran)\n");
        return;
    }
    gspHpokeState.executed = NV_TRUE;

    if ((pKernelGsp == NULL) || (pKernelGsp->pSysmemHeapDescriptor == NULL))
    {
        gspHpokeState.verdict = GSP_HPOKE_V_NO_HEAP_DESC;
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: no sysmem heap descriptor at +8 s "
                               "— the poke refuses (nothing written)\n");
        return;
    }
    if ((GSP_HPOKE_PLAN_N == 0) || (gspHpokePlan[0].sel == 0))
    {
        gspHpokeState.verdict = GSP_HPOKE_V_NULL_PLAN;
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: the plan is the GATED NULL "
                               "plan — no eligible candidate, nothing "
                               "to write (re-run v452b/v452c)\n");
        return;
    }

    // ---- the ONE entry for THIS boot (the selector filter) ----
    for (i = 0; i < GSP_HPOKE_PLAN_N; i++)
    {
        if (gspHpokePlan[i].sel == sel)
        {
            pEntry = &gspHpokePlan[i];
            break;
        }
    }
    if (pEntry == NULL)
    {
        gspHpokeState.verdict = GSP_HPOKE_V_SEL_NOT_IN_PLAN;
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: sel=%u (%s) not in the plan "
                               "(plan_sha16=%s) — nothing written\n",
                  sel, _gsp_hpoke_field_name(sel), GSP_HPOKE_PLAN_SHA16);
        return;
    }
    gspHpokeState.heapOffset = pEntry->heapOffset;
    gspHpokeState.len        = pEntry->len;

    // ---- the map: the radix3 WRITEABLE pattern @kernel_gsp.c:6028 ----
    sz = pKernelGsp->pSysmemHeapDescriptor->Size;
    if (pEntry->heapOffset + pEntry->len > sz)
    {
        gspHpokeState.verdict = GSP_HPOKE_V_BOUNDS;
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: plan offset 0x%llx beyond the "
                               "heap (0x%llx) — the plan is for another "
                               "heap size, nothing written\n",
                  pEntry->heapOffset, sz);
        return;
    }
    st = memdescMap(pKernelGsp->pSysmemHeapDescriptor, 0, sz,
                    NV_TRUE, NV_PROTECT_WRITEABLE,
                    (NvP64 *)&pVa, &pPriv);
    if ((st != NV_OK) || (pVa == NULL))
    {
        gspHpokeState.verdict = GSP_HPOKE_V_MAP_FAIL;
        NV_PRINTF(LEVEL_ERROR, "NVRM-452: the heap map FAILED st=0x%x — "
                               "nothing written\n", st);
        return;
    }
    pHeap = (NvU8 *)KERNEL_POINTER_FROM_NvP64(NvU8 *, pVa);

    // ---- the PRE-VERIFY: the runtime truth must match the plan ----
    {
        NvU8 oldSeen[8] = { 0 };
        char hexOld[32]  = { 0 };   // zero-init: the state copy publishes
        char hexWant[32] = { 0 };   // these bytes — no stack garbage in
                                    // the shared ledger

        for (i = 0; i < pEntry->len; i++)
            oldSeen[i] = pHeap[pEntry->heapOffset + i];
        _gsp_hpoke_hex(oldSeen, pEntry->len, hexOld, sizeof(hexOld));
        _gsp_hpoke_hex(pEntry->old, pEntry->len, hexWant, sizeof(hexWant));
        // the ledger copies (the state = the reliable surface; the
        // NV_PRINTF = the RM-debug bonus, never the reliance)
        for (i = 0; i < sizeof(gspHpokeState.hexSeen); i++)
            gspHpokeState.hexSeen[i] = hexOld[i];
        for (i = 0; i < sizeof(gspHpokeState.hexWant); i++)
            gspHpokeState.hexWant[i] = hexWant[i];

        for (i = 0; i < pEntry->len; i++)
        {
            if (oldSeen[i] != pEntry->old[i])
            {
                gspHpokeState.verdict = GSP_HPOKE_V_STALE_PLAN;
                NV_PRINTF(LEVEL_ERROR,
                          "NVRM-452: STALE-PLAN sel=%u (%s) off=0x%llx "
                          "seen=%s want=%s plan_sha16=%s — the runtime "
                          "moved (or the id-19 landmine) — ABORT, "
                          "nothing written\n",
                          sel, _gsp_hpoke_field_name(sel),
                          pEntry->heapOffset, hexOld, hexWant,
                          GSP_HPOKE_PLAN_SHA16);
                memdescUnmap(pKernelGsp->pSysmemHeapDescriptor, NV_TRUE,
                             pVa, pPriv);
                return;
            }
        }
        NV_PRINTF(LEVEL_INFO, "NVRM-452: pre-verify OK sel=%u (%s) "
                              "off=0x%llx seen=%s plan_sha16=%s\n",
                  sel, _gsp_hpoke_field_name(sel), pEntry->heapOffset,
                  hexOld, GSP_HPOKE_PLAN_SHA16);
    }

    // ---- the WRITE (byte-lane width, one field, no retry) ----
    for (i = 0; i < pEntry->len; i++)
        pHeap[pEntry->heapOffset + i] = pEntry->nw[i];

    // ---- the POST-VERIFY: the readback must equal the new bytes ----
    {
        NvU8 newSeen[8] = { 0 };
        NvBool ok = NV_TRUE;
        char hexNew[32] = { 0 };    // zero-init (the published ledger)

        for (i = 0; i < pEntry->len; i++)
            newSeen[i] = pHeap[pEntry->heapOffset + i];
        for (i = 0; i < pEntry->len; i++)
            ok = ok && (newSeen[i] == pEntry->nw[i]);
        _gsp_hpoke_hex(newSeen, pEntry->len, hexNew, sizeof(hexNew));
        for (i = 0; i < sizeof(gspHpokeState.hexNew); i++)
            gspHpokeState.hexNew[i] = hexNew[i];

        gspHpokeState.verdict  = GSP_HPOKE_V_WRITE_DONE;
        gspHpokeState.verifyOk = ok ? 1 : 0;
        NV_PRINTF(ok ? LEVEL_INFO : LEVEL_ERROR,
                  "NVRM-452: poke sel=%u (%s) off=0x%llx new=%s "
                  "verify=%s plan_sha16=%s\n",
                  sel, _gsp_hpoke_field_name(sel), pEntry->heapOffset,
                  hexNew, ok ? "OK" : "FAIL", GSP_HPOKE_PLAN_SHA16);
    }

    // ---- the unmap (the 4-arg pattern, kernel_gsp.c ~4033) ----
    memdescUnmap(pKernelGsp->pSysmemHeapDescriptor, NV_TRUE, pVa, pPriv);
}

// ---- the scheduler (the hook target — NO workqueue here) ----

void
gsp_hpoke_schedule(OBJGPU *pGpu, KernelGsp *pKernelGsp)
{
    NvU32 sel = 0;

    if (osReadRegistryDword(pGpu, "RmGspHPoke", &sel) != NV_OK)
        sel = 0; // default OFF — the opt-in writer, SEPARATE from the
                 // 4.51 dump key (the two instruments coexist cleanly)
    if ((sel == 0) || (sel > 5))
    {
        if (sel > 5)
        {
            gspHpokeState.verdict = GSP_HPOKE_V_BAD_SEL;
            NV_PRINTF(LEVEL_ERROR, "NVRM-452: RmGspHPoke=%u out of the "
                                   "selector domain {1..5} — OFF\n", sel);
        }
        // sel == 0: the silent OFF (the instrument absent — no verdict,
        // no ledger noise; the nv.c side prints the honest "off or the
        // hook never ran" line at +8 s)
        return;
    }

    if (gspHpokeState.scheduled)
        return;
    gspHpokeState.scheduled       = NV_TRUE;
    gspHpokeState.gpuId           = gpuGetDeviceInstance(pGpu);
    gspHpokeState.sel             = sel;   // the dedicated member — the
                                           // late fn reads THE boot's
                                           // selector from it
    gspHpokeState.pGpuSaved       = (void *)pGpu;
    gspHpokeState.pKernelGspSaved = (void *)pKernelGsp;
    gspHpokeState.pLateFn         = gsp_hpoke_late;   // the gc-sections
                                                      // law: the pointer
                                                      // keeps the fn alive
    {
        const char *fn = _gsp_hpoke_field_name(sel);
        NvU32 i;
        for (i = 0; (i < 7) && fn[i]; i++)
            gspHpokeState.fieldName[i] = fn[i];
        gspHpokeState.fieldName[i] = '\0';
    }
    {
        const char *sha = GSP_HPOKE_PLAN_SHA16;
        NvU32 i;
        for (i = 0; (i < 19) && sha[i]; i++)
            gspHpokeState.sha16[i] = sha[i];
        gspHpokeState.sha16[i] = '\0';
    }

    // NO schedule_delayed_work HERE — the workqueue = the nv.c side's
    // (patch_nv_452.py armed it at module init, +8 s). This hook ONLY
    // fills the state (the 4.51 v4 pattern).
    NV_PRINTF(LEVEL_INFO, "NVRM-452: gsp_hpoke armed sel=%u (%s) ONE field "
                          "this boot plan_sha16=%s — the nv.c side fires "
                          "at +8 s\n",
              sel, _gsp_hpoke_field_name(sel), GSP_HPOKE_PLAN_SHA16);
}
